n_workers = 7

kernel = "RBF"

max_len = 25
n_restarts = 10
n_samples = 1000

output = "inference/"

ref_config = "demos/dummy.toml"

# a dictionary with keys "X", "Y" and values torch tensors
D_init_path = "inference/data/prot.pth"

# observables and parameters need to match the ones used to create the D_init_path
[observables]
"R_int" = 7629550.6175
"M_planet" = 7.9643831975e+24
"transit_depth" = 0.00012026905833
"bond_albedo" = 0.25

[parameters]
"struct.mass_tot" = [0.5, 3.0]
"struct.corefrac" = [0.3, 0.9]
"atmos_clim.dummy.gamma" = [0.05, 0.95]
"escape.dummy.rate" = [1.0, 1e5]
"interior.dummy.ini_tmagma" = [2000, 4500]
"outgas.fO2_shift_IW" = [-4.0, 4.0]
