version = "2.0"
author = "Harrison Nicholls, Tim Lichtenberg, Mariana Sastre"

[params]
resume = false
offline = false
[params.out]
path = "minimal"
logging = "INFO"
plot_mod = 10
plot_fmt = "png"
write_mod = 1

[params.dt]
starspec = 3000000.0
starinst = 1000.0
method = "adaptive"
minimum = 300.0
minimum_rel = 1e-06
maximum = 10000000.0
initial = 1000.0

[params.dt.proportional]
propconst = 52.0

[params.dt.adaptive]
atol = 0.02
rtol = 0.1

[params.stop]
strict = false
[params.stop.iters]
enabled = true
minimum = 5
maximum = 9000

[params.stop.time]
enabled = true
maximum = 6000000000.0
minimum = 1000.0

[params.stop.solid]
phi_crit = 0.01
enabled = true

[params.stop.radeqm]
enabled = true
atol = 1.0
rtol = 0.001

[params.stop.escape]
enabled = true
p_stop = 1

[star]
module = "mors"
mass = 1.0
age_ini = 0.3

[star.mors]
age_now = 4.567
spec = "stellar_spectra/Named/sun.txt"
rot_pcntle = 50.0
rot_period = "none"
tracks = "spada"

[star.dummy]
radius = "none"
Teff = "none"

[orbit]
module = "dummy"
semimajoraxis = 1.0
eccentricity = 0.0
zenith_angle = 48.19
s0_factor = 0.375

[orbit.dummy]
H_tide = 0.0
Phi_tide = "<0.3"

[orbit.lovepy]
visc_thresh = 1000000000.0

[struct]
corefrac = 0.55
mass_tot = "none"
radius_int = 1.0
core_density = 10738.33
core_heatcap = 880.0

[atmos_clim]
module = "agni"
surf_state = "skin"
prevent_warming = false
surface_d = 0.01
surface_k = 2.0
cloud_enabled = false
cloud_alpha = 0.0
surf_greyalbedo = 0.2
albedo_pl = 0.0
rayleigh = true
tmp_minimum = 0.5
tmp_maximum = 5000.0

[atmos_clim.agni]
spectral_group = "Honeyside"
spectral_bands = "48"
p_top = 1e-05
surf_material = "surface_albedos/Hammond24/lunarmarebasalt.dat"
num_levels = 40
chemistry = "none"
solve_energy = true
solution_atol = 0.5
solution_rtol = 0.15
overlap_method = "ee"
condensation = false
real_gas = false

[atmos_clim.janus]
spectral_group = "none"
spectral_bands = "none"
p_top = 1e-05
p_obs = 0.002
F_atm_bc = 0
num_levels = 90
tropopause = "none"
overlap_method = "ee"

[atmos_clim.dummy]
gamma = 0.7

[escape]
module = "zephyrus"
reservoir = "outgas"

[escape.zephyrus]
Pxuv = 5e-05
efficiency = 0.1
tidal = false

[escape.dummy]
rate = "none"

[interior]
module = "spider"
melting_dir = "Monteux-600"
radiogenic_heat = true
tidal_heat = true
grain_size = 0.1
F_initial = 1000.0
rheo_phi_loc = 0.3
rheo_phi_wid = 0.15
bulk_modulus = 260000000000.0

[interior.spider]
ini_entropy = 2700.0
ini_dsdr = -4.698e-06
num_levels = 190
mixing_length = 2
tolerance = 1e-10
tolerance_rel = 1e-10
solver_type = "bdf"
tsurf_atol = 10.0
tsurf_rtol = 0.01

[interior.aragog]
logging = "ERROR"
ini_tmagma = "none"
num_levels = 120
tolerance = 1e-08

[interior.dummy]
ini_tmagma = "none"

[outgas]
fO2_shift_IW = 2.0
module = "calliope"

[outgas.calliope]
T_floor = 700.0
include_H2O = true
include_CO2 = true
include_N2 = true
include_S2 = true
include_SO2 = true
include_H2S = true
include_NH3 = true
include_H2 = true
include_CH4 = true
include_CO = true

[outgas.atmodeller]
some_parameter = "some_value"

[delivery]
module = "none"
initial = "elements"
radio_tref = 4.55
radio_K = 310.0
radio_U = 0.031
radio_Th = 0.124

[delivery.elements]
H_oceans = 1.0
H_ppmw = 0.0
CH_ratio = 1.0
C_ppmw = 0.0
NH_ratio = 0.0
N_ppmw = 1.0
SH_ratio = 2.0
S_ppmw = 0.0

[delivery.volatiles]
H2O = 0
CO2 = 0
N2 = 0
S2 = 0
SO2 = 0
H2S = 0
NH3 = 0
H2 = 0
CH4 = 0
CO = 0

[observe]
synthesis = "none"
