# PROTEUS configuration file (version 2.0)

# Root tables should be physical, with the exception of "params"
# Software related options should go within the appropriate physical table

# The general structure is:
#   [root]     metadata
#   [params]   parameters for code execution, output files, time-stepping, convergence
#   [star]     stellar parameters, model selection
#   [orbit]    planetary orbital parameters
#   [struct]   planetary structure (mass, radius)
#   [atmos]    atmosphere parameters, model selection
#   [escape]   escape parameters, model selection
#   [interior] magma ocean model selection and parameters
#   [outgas]   outgassing parameters (fO2) and included volatiles
#   [delivery] initial volatile inventory, and delivery model selection

# ----------------------------------------------------
# Metadata
version = "2.0"
author  = "Harrison Nicholls, Tim Lichtenberg"

# ----------------------------------------------------
# Parameters
[params]
    # output files
    [params.out]
        path        = "k218b"
        logging     = "DEBUG"
        plot_mod    = 1      # Plotting frequency, 0: wait until completion | n: every n iterations
        plot_fmt    = "png"  # Plotting image file format, "png" or "pdf" recommended

    # time-stepping
    [params.dt]
        minimum      = 3e2    # yr, minimum time-step
        maximum      = 1e7    # yr, maximum time-step
        initial      = 1e3    # yr, inital step size
        starspec     = 3e8    # yr, interval to re-calculate the stellar spectrum
        starinst     = 1e2    # yr, interval to re-calculate the instellation
        method       = "adaptive"  # proportional | adaptive | maximum

        [params.dt.proportional]
            propconst    = 52.0   # Proportionality constant

        [params.dt.adaptive]
            atol         = 0.03   # Step size atol
            rtol         = 0.15   # Step size rtol

    # Termination criteria
    #     Set enabled=true/false in each section to enable/disable that termination criterion
    [params.stop]

        # required number of iterations
        [params.stop.iters]
            enabled = true
            minimum = 3
            maximum = 9000

        # required time constraints
        [params.stop.time]
            enabled = true
            minimum = 1.0e3     # yr, model will certainly run to t > minimum
            maximum = 2.4e+9     # yr, model will terminate when t > maximum

        # solidification
        [params.stop.solid]
            enabled  = false
            phi_crit = 0.005  # non-dim., model will terminate when global melt fraction < phi_crit

        # radiative equilibrium
        [params.stop.radeqm]
            enabled = true
            atol    = 0.1     # absolute tolerance [W m-2]
            rtol    = 1e-3    # relative tolerance

        # steady state
        [params.stop.steady]
            enabled  = false
            F_crit   = 1.8        # Maximum absolute value of F_atm allowed for convergence
            dprel    = 3.0e-10     # Percentage change in melt fraction over time (dp/p)/dt*100

        [params.stop.escape]
            enabled   = false
            mass_frac = 3e-4      # Stop when atm_mass < this frac of initial mass


# ----------------------------------------------------
# Star
[star]

    # Physical parameters
    mass    = 0.495      # M_sun
    age_ini = 0.100     # Gyr, model initialisation/start age

    module  = "mors"
    [star.mors]
        rot_pctle = 50.0    # rotation percentile
        tracks  = "spada" # evolution tracks: spada | baraffe
        age_now = 2.4     # Gyr, current age of star used for scaling
        spec    = "stellar_spectra/Named/gj176.txt" # stellar spectrum

    [star.dummy]
        radius  = 0.912     # R_sun
        Teff    = 5772.0    # K

# Orbital system
[orbit]
    semimajoraxis   = 0.15910    # AU
    eccentricity    = 0.09      # dimensionless
    zenith_angle    = 54.74     # degrees
    s0_factor       = 0.25      # dimensionless

    module  = "none"

    [orbit.dummy]
        H_tide  = 1e-11  # Fixed tidal power density [W kg-1]


# Planetary structure - physics table
[struct]
    set_by      = 'mass_tot' # Variable to set interior structure: 'radius_int' or 'mass_tot'
    mass_tot    = 8.63       # M_earth
    radius_int  = 1.0       # R_earth
    corefrac    = 0.75      # non-dim., radius fraction

# Atmosphere - physics table
[atmos_clim]
    prevent_warming = true      # do not allow the planet to heat up
    surface_d       = 0.01      # m, conductive skin thickness
    surface_k       = 2.0       # W m-1 K-1, conductive skin thermal conductivity
    cloud_enabled   = false     # enable water cloud radiative effects
    cloud_alpha     = 0.0       # condensate retention fraction (1 -> fully retained)
    surf_state      = "fixed"    # surface scheme: "mixed_layer" | "fixed" | "skin"
    surf_greyalbedo = 0.0       # surface grey albedo
    albedo_pl       = 0.0   	# Enforced Bond albedo (do not use with `rayleigh = true`)
    rayleigh        = true      # Enable rayleigh scattering
    tmp_minimum     = 0.5           # temperature floor on solver
    tmp_maximum     = 5000.0        # temperature ceiling on solver

    module  = "agni"           # Which atmosphere module to use

    [atmos_clim.agni]
        p_top           = 1.0e-5        # bar, top of atmosphere grid pressure
        spectral_group  = "Dayspring"   # which gas opacities to include
        spectral_bands  = "48"         # how many spectral bands?
        num_levels      = 30           # Number of atmospheric grid levels
        chemistry       = "none"        # "none" | "eq"
        surf_material   = "greybody"    # surface material file for scattering
        solution_atol   = 1e-2          # solver absolute tolerance
        solution_rtol   = 1e-1          # solver relative tolerance
        overlap_method  = "ee"          # gas overlap method

    [atmos_clim.janus]
        p_top           = 1.0e-5        # bar, top of atmosphere grid pressure
        spectral_group  = "Dayspring"   # which gas opacities to include
        spectral_bands  = "48"         # how many spectral bands?
        F_atm_bc        = 0             # measure outgoing flux at: (0) TOA | (1) Surface
        num_levels      = 90            # Number of atmospheric grid levels
        tropopause      = "none"        # none | skin | dynamic
        overlap_method    = "ee"          # gas overlap method

    [atmos_clim.dummy]
        gamma           = 0.3           # atmosphere opacity between 0 and 1

# Volatile escape - physics table
[escape]

    module = "zephyrus"    # Which escape module to use

    [escape.zephyrus]
        Pxuv        = 1e-2          # Pressure at which XUV radiation become opaque in the planetary atmosphere [bar]
        efficiency  = 1.0           # Escape efficiency factor
        tidal       = false         # Tidal contribution enabled

    [escape.dummy]
        rate        = 0.0           # Bulk unfractionated escape rate [kg s-1]

# Interior - physics table
[interior]
    grain_size      = 0.1   # crystal settling grain size [m]
    F_initial       = 1e5   # Initial heat flux guess [W m-2]

    module = "aragog"   # Which interior module to use

    [interior.spider]
        num_levels      = 110       # Number of SPIDER grid levels
        mixing_length   = 2         # Mixing length parameterization
        tolerance       = 1.0e-7   # solver tolerance
        tsurf_atol      = 20.0      # tsurf_poststep_change
        tsurf_rtol      = 0.01      # tsurf_poststep_change_frac
        ini_entropy     = 3000.0    # Surface entropy conditions [J K-1 kg-1]
        ini_dsdr        = -4.698e-6 # Interior entropy gradient [J K-1 kg-1 m-1]

    [interior.aragog]
        num_levels      = 100       # Number of Aragog grid levels
        tolerance       = 1.0e-7   # solver tolerance
        ini_tmagma      = 3000.0    # Initial magma surface temperature [K]

    [interior.dummy]
        ini_tmagma      = 3500.0    # Initial magma surface temperature [K]

# Outgassing - physics table
[outgas]
    fO2_shift_IW    = -2         # log10(Î”IW), atmosphere/interior boundary oxidation state

    module = "calliope"         # Which outgassing module to use

    [outgas.calliope]
        include_H2O  = true     # Include H2O compound
        include_CO2  = true     # Include CO2 compound
        include_N2   = true     # Include N2 compound
        include_S2   = true     # Include S2 compound
        include_SO2  = true     # Include SO2 compound
        include_H2   = true     # Include H2 compound
        include_CH4  = true     # Include CH4 compound
        include_CO   = true     # Include CO compound
        T_floor      = 700.0    # Temperature floor applied to outgassing calculation [K].

    [outgas.atmodeller]
        some_parameter = "some_value"

# Volatile delivery - physics table
[delivery]

    # [Settings here for accretion rate, etc.]

    # Which initial inventory to use?
    initial = 'elements'        # "elements" | "volatiles"

    # No module for accretion as of yet
    module = "none"

    # Set initial volatile inventory by planetary element abundances
    [delivery.elements]
        CH_ratio    = 0.1       # C/H ratio in mantle/atmosphere system
        H_oceans    = 60.0       # Hydrogen inventory in units of equivalent Earth oceans, by mass
        N_ppmw      = 2.01      # Nitrogen inventory in ppmw relative to mantle mass, by mass
        S_ppmw      = 235.0     # Sulfur inventory in ppmw relative to mass of melt

    # Set initial volatile inventory by partial pressures in atmosphere
    [delivery.volatiles]
        H2O  = 0.0           # partial pressure of H2O
        CO2  = 0.0          # partial pressure of CO2
        N2   = 0.0          # etc
        S2   = 0.0
        SO2  = 0.0
        H2   = 0.0
        CH4  = 0.0
        CO   = 0.0
