########## PROTEUS configuration file

##### Star configuration

star_model                  = 1                 # Evolution model to use for star (0: Spada, 1: Baraffe)
star_mass                   = 0.401                # M_sun, mass of star
star_radius_modern          = 0.374                 # R_sun, radius of star (TODAY)
star_temperature_modern     = 3331.0             # K, temperature of star (TODAY)
star_luminosity_modern      = 0.167                 # L_sun, luminosity of star (TODAY) used for Baraffe model
star_age_modern             = 3.1e9             # yr, age of star (TODAY)
star_rot_pctle              = 20.0
star_spectrum               = 'stellar_spectra/Named/gj849.txt'   # Stellar spectrum file at 1 AU (TODAY)

##### Planet configuration
mean_distance               = 0.01203       # AU, star-planet distance
mass                        = 2.34         # M_earth
radius                      = 1.35         # R_earth

zenith_angle                = 54.74    # Tidally locked [Hamano+15,  acos(1/sqrt(3)) ]
asf_scalefactor             = 0.25     # absorbed solar flux scale factor = 1/4
albedo_s                    = 0.2 		# surface albedo
albedo_pl                   = 0.0   	# Bond albedo (scattering)

eccentricity                = 0.064     # Earth eccentricity  [dimensionless]

P_top                       = 1.0e-5    # bar, Pressure at TOA

##### PROTEUS settings

iter_max                    = 9000
log_level                   = 'INFO'

# Output subdirectory name (relative to output folder)
dir_output                  = 'ltt3780b'

# Choose times
time_star                   = 100.0e6  	# yr, time since star formation
time_target                 = 4.567e+9  # yr, target time for MO evolution

# SOCRATES spectral file to use (relative to FWL_DATA folder)
spectral_file               = 'spectral_files/Honeyside/256/Honeyside.sf'

# Stellar heating toggle, 0: disabled | 1: enabled
stellar_heating             = 1

# Time-stepping stuff
plot_iterfreq               = 1     # Plotting frequency, 0: wait until completion | n: every n iterations
plot_format                 = 'png'  # Plotting image file format
sspec_dt_update             = 2e6    # Time intervals at which to re-calculate the stellar spectrum
sinst_dt_update             = 1e2    # Time intervals at which to re-calculate the instellation
dt_maximum                  = 3e6    # Maximum time-step
dt_minimum                  = 3e2    # Minimum time-step
dt_method                   = 1      # Time-stepping method, 0: proportional | 1: adaptive | 2: maximum
dt_propconst                = 52.0   # Proportionality constant for dt_method=0
dt_atol                     = 0.02   # Step size atol
dt_rtol                     = 0.07   # Step size rtol
dt_initial                  = 1e3    # Inital step size

# Flux convergence scheme and tolerances for surface equilibration
shallow_ocean_layer         = 0         # 0: off | 1: on
F_atm_bc                    = 0         # Boundary condition choice for F_atm, 0: TOA | 1: Surface
skin_d                      = 0.01      # m
skin_k                      = 2.0       # W m-1 K-1
prevent_warming             = 1         # Require that the planet only cool down over time, 0: disabled | 1: enabled

# Break at solidification?
solid_stop                  = 1
phi_crit                    = 0.008     # melt fraction

# Break at steady state?
steady_stop                 = 1
steady_flux                 = 0.8        # Maximum absolute value of F_atm allowed for convergence
steady_dprel                = 1.0e-8     # Percentage change in melt fraction over time (dp/p)/dt*100

# Break at small flux?
emit_stop                   = 1         # Enable this break condition
F_crit                      = 0.1       # Model will terminate when |F_atm| < F_crit

# Atmospheric escape
escape_model                = 0         # Escape model to be used, 0: None | 1: ZEPHYRUS | 2: Dummy
escape_stop                 = 3e-4      # Terminate when atm mass drops below this fraction of its initial mass
escape_dummy_rate           = 0.0       # Bulk escape rate for dummy escape model [kg s-1]


# Method for solving for T(p) profile
atmosphere_model            = 1         # Atmosphere model to be used, 0: JANUS | 1: AGNI
atmosphere_surf_state       = 2         # Atmosphere bottom edge boundary condition, 0: free | 1: fixed at T_surf | 2: conductive skin

# Number of levels
atmosphere_nlev             = 48

# Temperature limits throughout atmosphere [K]
min_temperature             = 0.5
max_temperature             = 5000.0

# Clouds
water_cloud                 = 0         # enable water cloud radiative effects? (1: yes, 0: no)
alpha_cloud                 = 0.0       # condensate retention fraction (1 -> fully retained)

# Tropopause type, 0: none | 1: skin temperature | 2: dynamic
tropopause                  = 1

# Rayleigh scattering, 0: Disabled | 1: Enabled
rayleigh                    = 1

# Atmospheric chemistry, 0: Disabled | 1: Equilibrium | 2: Kinetics
atmosphere_chemistry       = 0

##### Interior-specific settings

interior_model              = 0
interior_nlev               = 220
grain_size                  = 0.1

# Mixing length parameterization: 1: variable | 2: constant
mixing_length               = 2

# Standard tolerance for solvers
solver_tolerance            = 1.0e-10

# Maximum absolute surface temperature change [K]
tsurf_poststep_change       = 20.0

# Maximum fractional surface temperature change [fraction]
tsurf_poststep_change_frac  = 0.01

# Fractional core radius
planet_coresize             = 0.55

# Initial entropy conditions for interior
ic_adiabat_entropy          = 3200.0
ic_dsdr                     = -4.698e-06

# Atmosphere heat flux start guess, adjusted during runtime [W/m^2]
F_atm                       = 1e5

# Oxygen fugacity offset relative to the IW buffer (log10 units)
fO2_shift_IW                = 0

# Enable solving for initial partial pressures (0: off | 1: on)
solvevol_use_params          = 1

# Parameters used to solve for initial partial pressures (when solvepp_use_params = 1)
Phi_global                  = 1.0       # Mantle melt fraction initial guess
CH_ratio                    = 1.0       # C/H ratio
hydrogen_earth_oceans       = 8.0       # Hydrogen inventory in units of equivalent Earth oceans
nitrogen_ppmw               = 2.01      # Nitrogen inventory in ppmw relative to mantle mass
sulfur_ppmw                 = 235.0     # Sulfur inventory in ppmw relative to mass of melt

# Prescribed injected partial pressures [bar]
H2O_included                = 1
H2O_initial_bar             = 0.0

CO2_included                = 1
CO2_initial_bar             = 0.0

N2_included                 = 1
N2_initial_bar              = 0.0

S2_included                 = 1
S2_initial_bar              = 0.0

SO2_included                = 1
SO2_initial_bar             = 0.0

H2_included                 = 1
H2_initial_bar              = 0.0

CH4_included                = 1
CH4_initial_bar             = 0.0

CO_included                 = 1
CO_initial_bar              = 0.0
