# Minimal PROTEUS configuration example.
# Only a few example science-critical parameters are set here to illustrate
# how a minimal physics-based config file can be structured. All parameters
# have defaults, which are listed in the documentation and in all_options.toml.
# Empty sections can be omitted entirely.
version = "3.0"

[star.mors]
    rot_pcntle      = 50.0
    age_now         = 4.567
    spectrum_source = "solar"
    star_name       = "sun"

[orbit]
    semimajoraxis = 1.0              # [AU]

[planet]
    mass_tot      = 1.0              # [M_earth]
    volatile_mode = "elements"
    [planet.elements]
        H_mode   = "oceans"
        H_budget = 5.0               # [Earth oceans]

[outgas]
    fO2_shift_IW = 4                 # [log10 delta IW]

[atmos_clim]
    spectral_group = "Honeyside"
    spectral_bands = "48"
