# Minimal PROTEUS configuration example.
# Only a few example science-critical parameters are set here to illustrate
# how a minimal physics-based config file can be structured. All parameters
# have defaults, which are listed in the documentation and in all_options.toml.
# Empty sections can be omitted entirely.
version = "3.0"

[orbit]
    semimajoraxis = 1.0              # [AU]

[planet]
    mass_tot      = 1.0              # [M_earth]
    volatile_mode = "elements"
    [planet.elements]
        H_mode   = "oceans"
        H_budget = 0.5               # [Earth oceans]

[outgas]
    fO2_shift_IW = 4                 # [log10 delta IW]
