# PROTEUS configuration file (version 2.0)

# This is a minimal outline of a PROTEUS configuration file. Since it only has a few
# options specified, the simulation will rely on the defaults.

# ----------------------------------------------------
version = "2.0"
author  = "Harrison Nicholls, Tim Lichtenberg, Mariana Sastre"

[params]
    [params.out]
        path        = "minimal"

[star]
    mass    = 1.0       # M_sun
    age_ini = 0.100     # Gyr, model initialisation/start age
    module  = "mors"
    [star.mors]
        rot_pcntle = 50.0    # rotation percentile
        age_now = 4.567     # Gyr, current age of star used for scaling
        spec    = "stellar_spectra/Named/sun.txt" # stellar spectrum

[orbit]
    semimajoraxis   = 1.0       # AU
    eccentricity    = 0.0       # dimensionless
    zenith_angle    = 48.19     # degrees
    s0_factor       = 0.375     # dimensionless
    module          = "dummy"

[struct]
    radius_int  = 1.0    # R_earth
    corefrac    = 0.65   # non-dim., radius fraction

[atmos_clim]
    module  = "agni"           # Which atmosphere module to use

    [atmos_clim.agni]
        spectral_group  = "Honeyside"   # which gas opacities to include
        spectral_bands  = "48"          # how many spectral bands?

[escape]
    module = "zephyrus"

[interior]
    module = "aragog"
    [interior.aragog]
        ini_tmagma      = 3000.0    # Initial magma surface temperature [K]

[outgas]
    fO2_shift_IW    = 4         # log10(Î”IW), atmosphere/interior boundary oxidation state
    module = "calliope"         # Which outgassing module to use

[delivery]
    initial = 'elements'        # Which initial inventory to use?
    module = "none"

    # Set initial volatile inventory by planetary element abundances
    [delivery.elements]
        H_oceans    = 5.0       # Hydrogen inventory in units of equivalent Earth oceans
        CH_ratio    = 1.0       # C/H mass ratio in mantle/atmosphere system
        N_ppmw      = 1.0       # Nitrogen inventory in ppmw relative to mantle mass
        SH_ratio    = 2.0       # S/H mass ratio in mantle/atmosphere system

# Calculate simulated observations
[observe]

    # Module with which to calculate the synthetic observables
    synthesis = "none"
