# PROTEUS configuration file (version 2.0)

# Root tables should be physical, with the exception of "exec"
# Software related options should go within the appropriate physical table

# The general structure is:
#   [meta]     metadata
#   [exec]     code execution, output files, time-stepping, convergence
#   [star]     stellar parameters, model selection
#   [orbit]    planetary orbital parameters
#   [struct]   planetary structure (mass, radius)
#   [atmos]    atmosphere parameters, model selection
#   [escape]   escape parameters, model selection
#   [interior] magma ocean model selection and parameters
#   [outgas]   outgassing parameters (fO2) and included volatiles
#   [delivery] initial volatile inventory, and delivery model selection

# ----------------------------------------------------
# Metadata
version = "2.0"
author  = "Harrison Nicholls"

# ----------------------------------------------------
# Parameters
[exec]
    # output files
    [exec.out]
        path        = "new_config_test"
        logging     = "DEBUG"
        plot_mod    = 1      # Plotting frequency, 0: wait until completion | n: every n iterations
        plot_fmt    = "png"  # Plotting image file format

    # time-stepping
    [exec.dt]
        minimum      = 1e2    # Minimum time-step
        maximum      = 3e7    # Maximum time-step
        initial      = 1e2    # Inital step size
        starspec     = 1e9    # Interval to re-calculate the stellar spectrum
        starinst     = 1e1    # Interval to re-calculate the instellation
        method = "adaptive"  # proportional | adaptive | maximum

        [exec.dt.proportional]
            propconst    = 52.0   # Proportionality constant

        [exec.dt.adaptive]
            atol         = 0.02   # Step size atol
            rtol         = 0.10   # Step size rtol

    # termination criteria...
    [exec.stop]

        # required number of iterations
        [exec.stop.iters]
            enabled = true
            minimum = 3
            maximum = 9000

        # required time constraints
        [exec.stop.time]
            enabled = true
            minimum = 1.0e3     # yr
            maximum = 4.0e9     # yr

        # solidification
        [exec.stop.solid]
            enabled  = true
            phi_crit = 0.005  # Critical melt fraction

        # radiative equilibrium
        [exec.stop.radeqm]
            enabled = true
            F_crit  = 0.2     # Model will terminate when |F_atm| < F_crit

        # steady state
        [exec.stop.steady]
            enabled  = true
            F_crit   = 0.8        # Maximum absolute value of F_atm allowed for convergence
            dprel    = 1.0e-9     # Percentage change in melt fraction over time (dp/p)/dt*100

        [exec.stop.escape]
            enabled   = true
            mass_frac = 3e-4      # Stop when atm_mass < this frac of initial mass


# ----------------------------------------------------
# Star
[star]

    # Physical parameters
    mass    = 1.0       # M_sun
    radius  = 1.0       # R_sun
    Teff    = 5772.0    # K
    Lbol    = 1.0       # L_sun
    omega   = 50.0      # rotation percentile
    age_now = 4.597     # Gyr, current age
    age_ini = 0.100     # Gyr, model initialisation age

    module  = "mors"
    [star.mors]
        tracks  = "spada"   # evolution tracks
        spec    = "stellar_spectra/Named/sun.txt"

# Orbital system
[orbit]
    semimajoraxis   = 1.0       # AU
    eccentricity    = 0.017     # dimensionless
    zenith_angle    = 48.19     # degrees
    s0_factor       = 0.375     # dimensionless

    # No module for this
    module  = "none"


# Planetary structure - physics table
[struct]
    mass        = 1.0       # M_earth
    radius      = 1.0       # R_earth
    corefrac    = 0.55      # [dimensionless]

    # No module for this
    module  = "none"

# Atmosphere - physics table
[atmos]
    prevent_warming = true
    surface_d       = 0.01      # m
    surface_k       = 2.0       # W m-1 K-1
    cloud_enabled   = false     # enable water cloud radiative effects?
    cloud_alpha     = 0.0       # condensate retention fraction (1 -> fully retained)
    surf_state      = 2
    surf_albedo     = 0.2       # path to file (string) or grey quantity (float)
    rayleigh        = true

    module  = "dummy"
    [atmos.agni]
        p_top           = 1.0e-5    # bar
        spectralfile    = "spectral_files/Frostflow/48/Frostflow.sf"
        num_levels      = 50
        chemistry       = "none"
        tmp_minimum     = 1.0

    [atmos.janus]
        p_top           = 1.0e-6    # bar
        spectralfile    = "spectral_files/Frostflow/48/Frostflow.sf"
        F_atm_bc        = 0         # boundary condition choice for F_atm
        num_levels      = 120
        tmp_minimum     = 0.2
        tropopause      = "skin"    # none | skin | dynamic

    [atmos.dummy]
        gamma           = 0.7

# Volatile escape - physics table
[escape]

    module = "dummy"
    [escape.zephyrus]
        some_parameter = "some_value"

    [escape.dummy]
        rate = 2.0e7    #  Bulk escape rate for dummy escape model [kg s-1]

# Interior - physics table
[interior]
    grain_size      = 0.1
    F_initial       = 1e6   # Initial heat flux guess [W m-2]

    module = "spider"
    [interior.spider]
        num_levels      = 220
        mixing_length   = 2         # Mixing length parameterization
        tolerance       = 1.0e-10
        tsurf_atol      = 30.0      # tsurf_poststep_change
        tsurf_rtol      = 0.02      # tsurf_poststep_change_frac
        ini_entropy     = 2700.0    # Initial entropy conditions for interior
        ini_dsdr        = -4.698e-6 # ^^

    [interior.aragog]
        some_parameter = "some_value"

# Outgassing - physics table
[outgas]
    fO2_shift_IW    = 2.0

    module = "calliope"
    [outgas.calliope]
        include_H2O  = true
        include_CO2  = true
        include_N2   = true
        include_S2   = true
        include_SO2  = true
        include_H2   = true
        include_CH4  = true
        include_CO   = true

    [outgas.atmodeller]
        some_parameter = "some_value"

# Volatile delivery - physics table
[delivery]

    # [Settings here for accretion rate, etc.]

    # Which initial inventory to use?
    initial = 'elements'

    # Set by elements
    [delivery.initial_elems]
        CH_ratio    = 1.0       # C/H ratio
        H_oceans    = 6.0       # Hydrogen inventory in units of equivalent Earth oceans
        N_ppmw      = 2.0       # Nitrogen inventory in ppmw relative to mantle mass
        S_ppmw      = 200.0     # Sulfur inventory in ppmw relative to mass of melt

    # Set by volatiles
    [delivery.initial_vols]
        H2O  = 30.0
        CO2  = 0.0
        N2   = 0.0
        S2   = 0.0
        SO2  = 0.0
        H2   = 0.0
        CH4  = 0.0
        CO   = 0.0

    module = "none"
