config_version = "3.0"

[params.out]
    path = "tutorial_sub_neptune"

[params.dt]
    initial = 1e2
    minimum = 1e2
    maximum = 1e7

    [params.stop.time]
        maximum = 5e9
    [params.stop.solid]
        phi_crit = 0.005

[star]
    module  = "mors"
    mass    = 0.8
    age_ini = 0.01
    [star.mors]
        tracks          = "spada"
        spectrum_source = "phoenix"

[orbit]
    semimajoraxis = 0.1

[planet]
    mass_tot         = 5.0
    temperature_mode = "liquidus_super"
    delta_T_super    = 500.0
    volatile_mode    = "elements"
    [planet.elements]
        H_mode   = "oceans"
        H_budget = 10.0
        C_mode   = "C/H"
        C_budget = 0.5
        N_mode   = "N/H"
        N_budget = 0.3
        S_mode   = "S/H"
        S_budget = 0.5

[interior_struct]
    module    = "zalmoxis"
    core_frac = 0.30

[interior_energetics]
    module = "boundary"

[outgas]
    module       = "calliope"
    fO2_shift_IW = 2

[atmos_clim]
    module     = "agni"
    surf_state = "fixed"

[escape]
    module = "zephyrus"
    [escape.zephyrus]
        efficiency = 0.1
