coverage:
  status:
    project:
      default:
        target: auto
    patch:
      default:
        target: 80%
flags:
  unit-tests:
    paths:
      - src/
    carryforward: true
  nightly:
    paths:
      - src/
    carryforward: true
