site_name: PROTEUS
site_url: https://fwl-proteus.readthedocs.io
repo_url: https://github.com/FormingWorlds/PROTEUS
repo_name: GitHub

nav:
  - Home: index.md
  - Model description: model.md
  - Installing PROTEUS:
    - Installation: installation.md
    - Machine specifics:
      - Local machines: local_machine_guide.md
      - Kapteyn cluster: kapteyn_cluster_guide.md
      - Snellius cluster: snellius_cluster_guide.md
      - Habrok cluster: habrok_cluster_guide.md
    - Troubleshooting: troubleshooting.md
  - Using PROTEUS:
    - Running simulations: usage.md
    - Configuration: config.md
    - Reference data: data.md
    - Bibliography: bibliography.md
    - Bayesian inference (alpha): inference.md
  - Developing PROTEUS:
    - Contributing: CONTRIBUTING.md
  - Continuous Integration:
    - Test infrastructure: test_infrastructure.md
    - Building tests: test_infrastructure.md
  - Contact: contact.md
  - Code of Conduct: CODE_OF_CONDUCT.md
  - Funding: funding.md
  - Source code: https://github.com/FormingWorlds/PROTEUS
  - Issues page: https://github.com/FormingWorlds/PROTEUS/issues
  - PROTEUS ecosystem:
    - 🔗 MORS:  https://fwl-mors.readthedocs.io/
    - 🔗 JANUS: https://fwl-janus.readthedocs.io/
    - 🔗 ZEPHYRUS: https://github.com/FormingWorlds/ZEPHYRUS/
    - 🔗 CALLIOPE: https://fwl-calliope.readthedocs.io/
    - 🔗 AGNI: https://h-nicholls.space/AGNI/
    - 🔗 LovePy: https://github.com/nichollsh/lovepy
    - 🔗 VULCAN: https://github.com/FormingWorlds/VULCAN
    - 🔗 Zalmoxis: https://github.com/FormingWorlds/Zalmoxis
    - 🔗 Aragog: https://github.com/FormingWorlds/aragog
    - 🔗 SPIDER: https://github.com/djbower/spider

theme:
  name: material
  palette:
    primary: black
    accent: deep orange
  features:
    - navigation.expand

markdown_extensions:
  - admonition
  - attr_list
  - markdown_include.include:
      base_path: docs
  - pymdownx.extra
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
- search
- mkdocstrings:
    # https://mkdocstrings.github.io/usage/
    handlers:
      python:
        paths: [src]
        inventories:
        - https://installer.readthedocs.io/en/stable/objects.inv
        - https://docs.python.org/3/objects.inv
        - https://numpy.org/doc/stable/objects.inv
        - https://docs.scipy.org/doc/scipy/objects.inv
        - https://pandas.pydata.org/docs/objects.inv
        - https://matplotlib.org/stable/objects.inv
        options:
          docstring_style: numpy
          docstring_options:
            ignore_init_summary: yes
          show_submodules: no
          show_source: true
          show_symbol_type_heading: True
          show_root_heading: true
          show_root_toc_entry: true
          show_docstring_attributes: true
          show_root_full_path: false
          docstring_section_style: list
          members_order: alphabetical
          merge_init_into_class: yes
          filters: ["!^_"]

use_directory_urls: false

watch:
  - docs/
  - README.md
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
