site_name: PROTEUS
site_url: https://proteus-framework.org/PROTEUS/
repo_url: https://github.com/FormingWorlds/PROTEUS
repo_name: GitHub

copyright: '© 2023-2026 <a href="https://formingworlds.space">Forming Worlds Lab</a>'

nav:
  - Home:
      - About: index.md
      - Getting started: getting_started.md

  - How-to guides:
      - Getting started:
          - Install PROTEUS: How-to/installation.md
          - Configure PROTEUS: How-to/config.md
          - Usage: How-to/usage.md
          - Troubleshooting: How-to/troubleshooting.md
          - Run on a local machine: How-to/local_machine_guide.md
      - Advanced usage:
          - Bayesian inference: How-to/inference.md
      - Cluster guides:
          - Run on Kapteyn: How-to/kapteyn_cluster_guide.md
          - Run on Snellius: How-to/snellius_cluster_guide.md
          - Run on Habrok: How-to/habrok_cluster_guide.md
      - Development:
          - Testing infrastructure: How-to/test_infrastructure.md
          - Test categorization: How-to/test_categorization.md
          - Test building: How-to/test_building.md
          - AI-assisted development: How-to/ai_usage.md

  - Tutorials:
      - First PROTEUS run: How-to/usage.md

  - Explanations:
      - Model description: Explanations/model.md
      - Docker CI architecture: Explanations/docker_ci_architecture.md

  - Reference:
      - Reference data: Reference/data.md
      - Bibliography: Reference/bibliography.md

  - Community:
      - Contact: Community/contact.md
      - Contributing: Community/CONTRIBUTING.md
      - Code of Conduct: Community/CODE_OF_CONDUCT.md
      - Developers: https://proteus-framework.org/people
      - Issues: https://github.com/FormingWorlds/PROTEUS/issues

  - Funding: funding.md

  - Source code: https://github.com/FormingWorlds/PROTEUS

  - Submodules:
      - PROTEUS submodules: submodules.md
      - MORS: https://proteus-framework.org/MORS/
      - JANUS: https://proteus-framework.org/JANUS/
      - ZEPHYRUS: https://proteus-framework.org/ZEPHYRUS/
      - CALLIOPE: https://proteus-framework.org/CALLIOPE/
      - AGNI: https://www.h-nicholls.space/AGNI/
      - Obliqua: https://proteus-framework.org/Obliqua/
      - VULCAN: https://proteus-framework.org/VULCAN/
      - Zalmoxis: https://proteus-framework.org/Zalmoxis/
      - Aragog: https://proteus-framework.org/aragog/
      - SPIDER: https://proteus-framework.org/SPIDER/
      - Atmodeller: https://atmodeller.readthedocs.io/en/latest/
      - FastChem: https://newstrangeworlds.github.io/FastChem/
      - PLATON: https://platon.readthedocs.io/en/latest/
      - SOCRATES: https://github.com/FormingWorlds/SOCRATES/

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - content.code.copy
    - content.tabs.link


  # Default assets (used unless overridden per palette below)
  favicon: assets/PROTEUS_black_on_white_logo_only.png
  logo: assets/PROTEUS_white_on_black.png

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      favicon: assets/PROTEUS_black_on_white_logo_only.png
      logo: assets/PROTEUS_white_on_black.png
      toggle:
        icon: lucide/moon
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      favicon: assets/PROTEUS_white_on_black_logo_only.png
      logo: assets/PROTEUS_white_on_black.png
      toggle:
        icon: lucide/sun
        name: Switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - markdown_include.include:
      base_path: docs
  - pymdownx.extra
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# footer:
extra:
  generator: false
  social:
    - icon: material/web
      link: https://proteus-framework.org/
      name: PROTEUS website
    - icon: material/email
      link: mailto:proteus_dev@formingworlds.space
      name: Mail PROTEUS developers
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/fwl-proteus/
      name: PROTEUS on PyPI
    - icon: fontawesome/brands/github
      link: https://github.com/FormingWorlds/PROTEUS
      name: PROTEUS on GitHub

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/header-links.js

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          inventories:
            - https://installer.readthedocs.io/en/stable/objects.inv
            - https://docs.python.org/3/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://docs.scipy.org/doc/scipy/objects.inv
            - https://pandas.pydata.org/docs/objects.inv
            - https://matplotlib.org/stable/objects.inv
          options:
            docstring_style: numpy
            docstring_options:
              ignore_init_summary: yes
            show_submodules: no
            show_source: true
            show_symbol_type_heading: true
            show_root_heading: true
            show_root_toc_entry: true
            show_docstring_attributes: true
            show_root_full_path: false
            docstring_section_style: list
            members_order: alphabetical
            merge_init_into_class: yes
            filters: ["!^_"]

use_directory_urls: false

watch:
  - src/
  - docs/
  - README.md
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
