version = "2.0"
author = "Harrison Nicholls, Tim Lichtenberg"

[star]
mass = 1.0
age_ini = 0.1
module = "dummy"

[orbit]
semimajoraxis = 1.0
eccentricity = 0.0
zenith_angle = 48.19
s0_factor = 0.375
module = "dummy"

[struct]
mass_tot = 1.395590976107402
corefrac = 0.3546300929244785
core_density = 10738.33
core_heatcap = 880.0

[atmos_clim]
surf_state = "fixed"
albedo_pl = 0.1
module = "dummy"
rayleigh = false

[escape]
reservoir = "outgas"
module = "dummy"

[interior]
radiogenic_heat = false
tidal_heat = false
module = "dummy"

[outgas]
fO2_shift_IW = -4.0
module = "calliope"

[delivery]
initial = "elements"
module = "none"

[observe]
synthesis = "none"

[atmos_chem]
module = "none"

[params.out]
path = "inference/workers/w_4/i_4/"
logging = "ERROR"
plot_mod = 0
write_mod = 50
archive_mod = "none"

[params.dt]
minimum = 100.0
maximum = 30000000.0
initial = 100.0
starspec = 1000000000.0
starinst = 10.0
method = "adaptive"

[star.dummy]
radius = 1.0
Teff = 5772.0

[orbit.dummy]
H_tide = 1e-9
Phi_tide = "<0.3"

[orbit.lovepy]
visc_thresh = 1000000000.0

[atmos_clim.dummy]
gamma = 0.05

[escape.dummy]
rate = 1.0

[interior.dummy]
ini_tmagma = 4500.0

[delivery.elements]
H_ppmw = 200.0
CH_ratio = 1.0
N_ppmw = 2.0
SH_ratio = 1.0

[params.dt.adaptive]
atol = 0.02
rtol = 0.12

[params.stop.time]
enabled = true
minimum = 1000.0
maximum = 2000000000.0

[params.stop.solid]
enabled = false
phi_crit = 0.005

[params.stop.radeqm]
enabled = false
atol = 0.2
rtol = 0.001

[params.stop.escape]
enabled = true
p_stop = 1.0
