# PROTEUS configuration file (version 2.0)

version = "2.0"
author  = "Harrison Nicholls, Tim Lichtenberg"

[params]
    [params.out]
        path        = "k218b"
        logging     = "DEBUG"

    # time-stepping
    [params.dt]
        starspec     = 3e8    # yr, interval to re-calculate the stellar spectrum
        [params.dt.adaptive]
            atol         = 0.03   # Step size atol
            rtol         = 0.15   # Step size rtol

    [params.stop]
        [params.stop.time]
            enabled = true
            minimum = 1.0e3     # yr, model will certainly run to t > minimum
            maximum = 2.4e+9     # yr, model will terminate when t > maximum

        [params.stop.solid]
            enabled  = false

        [params.stop.radeqm]
            enabled = true
            atol    = 0.1     # absolute tolerance [W m-2]
            rtol    = 1e-3    # relative tolerance

[star]

    # Physical parameters
    mass    = 0.495      # M_sun
    age_ini = 0.100     # Gyr, model initialisation/start age

    module  = "mors"
    [star.mors]
        rot_pcntle = 50.0       # rotation percentile
        tracks  = "spada" # evolution tracks: spada | baraffe
        age_now = 2.4     # Gyr, current age of star used for scaling
        spec    = "stellar_spectra/Named/gj176.txt" # stellar spectrum

# Orbital system
[orbit]
    semimajoraxis   = 0.15910    # AU
    eccentricity    = 0.09      # dimensionless
    zenith_angle    = 54.74     # degrees
    s0_factor       = 0.25      # dimensionless
    module  = "none"

# Planetary structure - physics table
[struct]
    mass_tot    = 8.63       # M_earth
    corefrac    = 0.75      # non-dim., radius fraction

# Atmosphere - physics table
[atmos_clim]
    surf_state      = "fixed"    # surface scheme: "mixed_layer" | "fixed" | "skin"
    rayleigh        = true      # Enable rayleigh scattering

    module  = "agni"           # Which atmosphere module to use

    [atmos_clim.agni]
        p_top           = 1.0e-5        # bar, top of atmosphere grid pressure
        spectral_group  = "Dayspring"   # which gas opacities to include
        spectral_bands  = "48"         # how many spectral bands?
        num_levels      = 30           # Number of atmospheric grid levels
        chemistry       = "none"        # "none" | "eq"
        surf_material   = "greybody"    # surface material file for scattering
        solve_energy    = true         # solve for energy-conserving atmosphere profile
        solution_atol   = 1e-2          # solver absolute tolerance
        solution_rtol   = 1e-1          # solver relative tolerance
        overlap_method  = "ee"          # gas overlap method
        condensation    = true          # volatile condensation
        real_gas        = true          # use real-gas equations of state

[escape]

    module = "zephyrus"    # Which escape module to use

    [escape.zephyrus]
        Pxuv        = 1e-2          # Pressure at which XUV radiation become opaque in the planetary atmosphere [bar]
        efficiency  = 1.0           # Escape efficiency factor
        tidal       = false         # Tidal contribution enabled

[interior]
    radiogenic_heat = true  # enable radiogenic heat production
    tidal_heat      = false  # enable tidal heat production
    rheo_phi_loc    = 0.4    # Centre of rheological transition
    rheo_phi_wid    = 0.15   # Width of rheological transition
    bulk_modulus    = 260e9   # Bulk modulus [Pa]

    module = "aragog"   # Which interior module to use

    [interior.aragog]
        logging         = "ERROR"
        num_levels      = 100       # Number of Aragog grid levels
        tolerance       = 1.0e-7   # solver tolerance
        ini_tmagma      = 3000.0    # Initial magma surface temperature [K]

[outgas]
    fO2_shift_IW    = -2         # log10(Î”IW), atmosphere/interior boundary oxidation state
    module = "calliope"         # Which outgassing module to use


[delivery]

    # Which initial inventory to use?
    initial = 'elements'        # "elements" | "volatiles"

    # No module for accretion as of yet
    module = "none"

    # Set initial volatile inventory by planetary element abundances
    [delivery.elements]
        H_oceans    = 60.0       # Hydrogen inventory in units of equivalent Earth oceans
        # H_ppmw      = 0.0     # Hydrogen inventory in ppmw relative to mantle mass

        CH_ratio    = 0.1       # C/H mass ratio in mantle/atmosphere system
        # C_ppmw      = 0.0       # Carbon inventory in ppmw relative to mantle mass

        # NH_ratio    = 0.0       # N/H mass ratio in mantle/atmosphere system
        N_ppmw      = 2.01      # Nitrogen inventory in ppmw relative to mantle mass

        # SH_ratio    = 0.0       # S/H mass ratio in mantle/atmosphere system
        S_ppmw      = 235.0     # Sulfur inventory in ppmw relative to mantle mass

# Calculate simulated observations
[observe]
    synthesis = "none"

[atmos_chem]
    module = "none"
