# PROTEUS configuration file (version 2.0)

version = "2.0"
author  = "Harrison Nicholls, Tim Lichtenberg"

[params]
    [params.out]
        path        = "l9859d"
        logging     = "INFO"
        plot_mod    = 40      # Plotting frequency, 0: wait until completion | n: every n iterations
        write_mod   = 5

    # time-stepping
    [params.dt]
        minimum      = 3e2    # absolute minimum time-step [years]
        minimum_rel  = 5e-3   # relative minimum time-step [dimensionless]
        maximum      = 2e8    # yr, maximum time-step
        initial      = 1e4    # yr, inital step size
        starspec     = 9e9    # yr, interval to re-calculate the stellar spectrum
        starinst     = 1e2    # yr, interval to re-calculate the instellation
        method       = "adaptive"  # proportional | adaptive | maximum
        [params.dt.adaptive]
            atol         = 0.03  # Step size atol
            rtol         = 0.12   # Step size rtol

    [params.stop]

        [params.stop.time]
            enabled = true
            maximum = 4.94e9     # yr, model will terminate when t > maximum

        # solidification
        [params.stop.solid]
            enabled  = true
            phi_crit = 0.01

        # radiative equilibrium
        [params.stop.radeqm]
            enabled = false

        [params.stop.escape]
            enabled   = true
            p_stop    = 5.0  # bar, model will terminate with p_surf < p_stop


# ----------------------------------------------------
# Star
[star]

    mass    = 0.273      # M_sun
    age_ini = 0.05     # Gyr, model initialisation/start age

    module  = "mors"
    [star.mors]
        rot_period = 80.9       # rotation period
        tracks  = "spada" # evolution tracks: spada | baraffe
        age_now = 4.40     # Gyr, current age of star used for scaling
        spec    = "stellar_spectra/Named/l-98-59.txt" # stellar spectrum


[orbit]
    semimajoraxis   = 0.0486    # AU
    eccentricity    = 0.098      # dimensionless
    zenith_angle    = 54.74     # degrees
    s0_factor       = 0.25      # dimensionless

    module  = "lovepy"
    [orbit.lovepy]
        visc_thresh = 1e9   # Minimum viscosity required for heating [Pa s]

[struct]
    mass_tot    = 2.14       # M_earth
    corefrac    = 0.55      # non-dim., radius fraction

[atmos_clim]
    prevent_warming = true     # do not allow the planet to heat up
    surface_d       = 0.01      # m, conductive skin thickness
    surface_k       = 2.0       # W m-1 K-1, conductive skin thermal conductivity
    surf_state      = "skin"    # surface scheme: "mixed_layer" | "fixed" | "skin"
    rayleigh        = true     # Enable rayleigh scattering

    module  = "agni"           # Which atmosphere module to use

    [atmos_clim.agni]
        p_top           = 2.0e-5        # bar, top of atmosphere grid pressure
        spectral_group  = "Honeyside"   # which gas opacities to include
        spectral_bands  = "48"         # how many spectral bands?
        num_levels      = 40            # Number of atmospheric grid levels
        chemistry       = "none"        # "none" | "eq"
        surf_material   = "surface_albedos/Hammond24/lunarmarebasalt.dat"    # surface material file for scattering
        solve_energy    = true         # solve for energy-conserving atmosphere profile
        solution_atol   = 2.0          # solver absolute tolerance
        solution_rtol   = 0.13          # solver relative tolerance
        overlap_method  = "ee"          # gas overlap method
        condensation    = false         # volatile condensation
        real_gas        = true          # use real-gas equations of state

[escape]
    module = "zephyrus"
    [escape.zephyrus]
        Pxuv = 5e-5
        efficiency = 0.1
        tidal = false

[interior]
    F_initial       = 1e4   # Initial heat flux guess [W m-2]
    radiogenic_heat = true  # enable radiogenic heat production
    tidal_heat      = true  # enable tidal heat production
    rheo_phi_loc    = 0.3    # Centre of rheological transition
    rheo_phi_wid    = 0.15   # Width of rheological transition
    bulk_modulus    = 260e9   # Bulk modulus [Pa]

    module = "spider"   # Which interior module to use

    [interior.spider]
        num_levels      = 180       # Number of SPIDER grid levels
        mixing_length   = 2         # Mixing length parameterization
        tolerance       = 1e-10      # absolute solver tolerance
        tolerance_rel   = 1e-9      # relative solver tolerance
        tsurf_atol      = 5.0      # tsurf_poststep_change
        tsurf_rtol      = 0.02      # tsurf_poststep_change_frac
        ini_entropy     = 3000.0    # Surface entropy conditions [J K-1 kg-1]
        ini_dsdr        = -4.698e-6 # Interior entropy gradient [J K-1 kg-1 m-1]


[outgas]
    fO2_shift_IW    = 0         # log10(Î”IW), atmosphere/interior boundary oxidation state
    module = "calliope"         # Which outgassing module to use

[delivery]
    initial = 'elements'        # "elements" | "volatiles"
    module = "none"

    [delivery.elements]
        H_ppmw      = 109.0     # Hydrogen inventory in ppmw relative to mantle mass
        CH_ratio    = 1.0       # C/H mass ratio in mantle/atmosphere system
        NH_ratio    = 0.018       # N/H mass ratio in mantle/atmosphere system
        SH_ratio    = 7.5       # S/H mass ratio in mantle/atmosphere system

[observe]
    synthesis = "platon"

[atmos_chem]
    module = "none"
