# PROTEUS configuration file (version 2.0)

# Metadata
version = "2.0"
author  = "Harrison Nicholls, Tim Lichtenberg"

# ----------------------------------------------------
# Parameters
[params]
    [params.out]
        path        = "escape"
        plot_fmt    = "pdf"  # Plotting image file format, "png" or "pdf" recommended

    # time-stepping
    [params.dt]
        minimum      = 3e2    # yr, minimum time-step
        maximum      = 3e7    # yr, maximum time-step
        initial      = 1e4    # yr, inital step size
        starspec     = 1e9    # yr, interval to re-calculate the stellar spectrum
        starinst     = 100    # yr, interval to re-calculate the instellation
        [params.dt.adaptive]
            atol         = 0.02   # Step size atol
            rtol         = 0.07   # Step size rtol

    [params.stop]

        [params.stop.time]
            enabled = true
            minimum = 1.0e3     # yr, model will certainly run to t > minimum
            maximum = 4.567e+9     # yr, model will terminate when t > maximum

        [params.stop.solid]
            enabled  = true
            phi_crit = 0.005  # non-dim., model will terminate when global melt fraction < phi_crit

        [params.stop.radeqm]
            enabled = true
            atol    = 0.2     # absolute tolerance [W m-2]
            rtol    = 1e-3    # relative tolerance

        [params.stop.escape]
            enabled   = true
            p_stop    = 1.0  # bar, model will terminate with p_surf < p_stop


[star]

    # Physical parameters
    mass    = 1.0       # M_sun
    age_ini = 0.100     # Gyr, model initialisation/start age

    module  = "mors"
    [star.mors]
        rot_pcntle = 50.0       # rotation percentile
        tracks  = "spada"   # evolution tracks: spada | baraffe
        age_now = 4.567     # Gyr, current age of star used for scaling
        spec    = "stellar_spectra/Named/sun.txt" # stellar spectrum

[orbit]
    semimajoraxis   = 1.0       # AU
    eccentricity    = 0.0       # dimensionless
    zenith_angle    = 48.19     # degrees
    s0_factor       = 0.375     # dimensionless
    module  = "none"

[struct]
    mass_tot    = 1.0           # Total planet mass [M_earth]
    corefrac    = 0.55          # non-dim., radius fraction

# Atmosphere - physics table
[atmos_clim]
    prevent_warming = true      # do not allow the planet to heat up
    surface_d       = 0.01      # m, conductive skin thickness
    surface_k       = 2.0       # W m-1 K-1, conductive skin thermal conductivity
    surf_state      = "skin"    # surface scheme: "mixed_layer" | "fixed" | "skin"
    surf_greyalbedo  = 0.1      # surface grey albedo
    rayleigh        = true      # enable rayleigh scattering

    module  = "janus"           # Which atmosphere module to use

    [atmos_clim.janus]
        p_top           = 1.0e-7        # bar, top of atmosphere grid pressure
        p_obs           = 1.0e-3        # bar, observed pressure level
        spectral_group  = "Frostflow"   # which gas opacities to include
        spectral_bands  = "256"         # how many spectral bands?
        F_atm_bc        = 0             # measure outgoing flux at: (0) TOA | (1) Surface
        num_levels      = 250           # Number of atmospheric grid levels
        tropopause      = "skin"        # none | skin | dynamic
        overlap_method    = "ee"          # gas overlap method

[escape]

    reservoir = "bulk"  # Escaping reservoir: "bulk", "outgas", "pxuv".
    module = "zephyrus"    # Which escape module to use
    [escape.zephyrus]
        Pxuv        = 1e-2          # Pressure at which XUV radiation become opaque in the planetary atmosphere [bar]
        efficiency  = 1.0           # Escape efficiency factor
        tidal       = false         # Tidal contribution enabled


[interior]
    radiogenic_heat = true  # enable radiogenic heat production
    tidal_heat      = false  # enable tidal heat production

    module = "spider"   # Which interior module to use

    [interior.spider]
        num_levels      = 220       # Number of SPIDER grid levels
        mixing_length   = 2         # Mixing length parameterization
        tolerance       = 1.0e-10   # solver tolerance
        tsurf_atol      = 20.0      # tsurf_poststep_change
        tsurf_rtol      = 0.01      # tsurf_poststep_change_frac
        ini_entropy     = 2600.0    # Surface entropy conditions [J K-1 kg-1]
        ini_dsdr        = -4.698e-6 # Interior entropy gradient [J K-1 kg-1 m-1]

[outgas]
    fO2_shift_IW    = 4         # log10(Î”IW), atmosphere/interior boundary oxidation state

    module = "calliope"         # Which outgassing module to use

    [outgas.calliope]
        include_H2O  = true     # Include H2O compound
        include_CO2  = true     # Include CO2 compound
        include_N2   = true     # Include N2 compound
        include_S2   = true     # Include S2 compound
        include_SO2  = false    # Include SO2 compound
        include_H2S  = false     # Include H2S compound
        include_NH3  = false     # Include NH3 compound
        include_H2   = false    # Include H2 compound
        include_CH4  = false    # Include CH4 compound
        include_CO   = false    # Include CO compound

[delivery]

    # Which initial inventory to use?
    initial = 'volatiles'        # "elements" | "volatiles"

    # No module for accretion as of yet
    module = "none"

    # Set initial volatile inventory by partial pressures in atmosphere
    [delivery.volatiles]
        H2O  = 30.0         # partial pressure of H2O
        CO2  = 0.0          # partial pressure of CO2
        N2   = 0.0          # etc
        S2   = 0.0
        SO2  = 0.0
        H2S  = 0.0
        NH3  = 0.0
        H2   = 0.0
        CH4  = 0.0
        CO   = 0.0

# Calculate simulated observations
[observe]
    synthesis = "none"

[atmos_chem]
    module = "none"
