# PROTEUS configuration file (version 2.0)
version = "2.0"

[params]
    [params.out]
        path        = "orbit_physical"
        logging     = "INFO"
        plot_mod    = 10      # Plotting frequency, 0: wait until completion | n: every n iterations
        write_mod   = 10      # Write CSV frequency, 0: wait until completion | n: every n iterations
        archive_mod = 'none'

    [params.dt]
        minimum      = 1e3    # yr, minimum time-step
        maximum      = 3e7    # yr, maximum time-step
        initial      = 1e3    # yr, inital step size
        starspec     = 1e9    # yr, interval to re-calculate the stellar spectrum
        starinst     = 1e1    # yr, interval to re-calculate the instellation
        method       = "adaptive"  # proportional | adaptive | maximum

        [params.dt.adaptive]
            atol         = 0.02   # Step size atol
            rtol         = 0.10   # Step size rtol

    [params.stop]
        # required time constraints
        [params.stop.time]
            enabled = true
            minimum = 1.0e3     # yr, model will certainly run to t > minimum
            maximum = 1e9     # yr, model will terminate when t > maximum

        # solidification
        [params.stop.solid]
            enabled  = false
            phi_crit = 0.005  # non-dim., model will terminate when global melt fraction < phi_crit

        # radiative equilibrium
        [params.stop.radeqm]
            enabled = true
            atol    = 0.2     # absolute tolerance [W m-2]
            rtol    = 1e-3    # relative tolerance

        # atmospheric escape
        [params.stop.escape]
            enabled   = true
            p_stop    = 1.0   # bar, model will terminate with p_surf < p_stop

        # disintegration
        [params.stop.disint]
            enabled   = true

            roche_enabled = true
            offset_roche  = 0 # correction to calculated Roche limit [m]

            spin_enabled  = true
            offset_spin   = 0 # correction to calculated Breakup period [s]


# Star
[star]

    # Physical parameters
    mass    = 1.0       # stellar mass [M_sun]
    age_ini = 0.100     # model initialisation age [Gyr]

    module  = "dummy"

    [star.dummy]
        radius  = 1.0       # Stellar radius [R_sun]
        Teff    = 5772.0    # Star's brightness temperature [K]

# Orbital system
[orbit]
    semimajoraxis   = 0.03       # AU
    eccentricity    = 0.8       # dimensionless
    zenith_angle    = 48.19     # degrees
    s0_factor       = 0.375     # dimensionless
    axial_period    = 'none'    # hours, or provide 'none' to set as tidally locked

    evolve  = true

    satellite = false
    semimajoraxis_sat = 300e6

    module  = "lovepy"

    [orbit.dummy]
        H_tide   = 1e-9     # Fixed tidal power density [W kg-1]
        Phi_tide = "<0.3"   # Tidal heating applied when inequality locally satisfied
        Imk2     = -1e5     # Fixed Im(k2) love number

    [orbit.lovepy]
        visc_thresh = 1e9   # Minimum viscosity required for heating [Pa s]

# Planetary structure - physics table
[struct]
    mass_tot     = 1.0           # Total planet mass [M_earth]
    corefrac     = 0.55          # non-dim., radius fraction
    core_density = 10738.33      # Core density [kg m-3]
    core_heatcap = 880.0         # Core specific heat capacity [J K-1 kg-1]

# Atmosphere - physics table
[atmos_clim]
    prevent_warming = false      # do not allow the planet to heat up
    surface_d       = 0.01      # m, conductive skin thickness
    surface_k       = 2.0       # W m-1 K-1, conductive skin thermal conductivity
    cloud_enabled   = false     # enable water cloud radiative effects
    cloud_alpha     = 0.0       # condensate retention fraction (1 -> fully retained)
    surf_state      = "fixed"   # surface scheme: "mixed_layer" | "fixed" | "skin"
    surf_greyalbedo  = 0.1      # surface grey albedo
    albedo_pl       = 0.0   	# Bond albedo (scattering)
    rayleigh        = false      # enable rayleigh scattering
    tmp_minimum     = 0.5       # temperature floor on solver
    tmp_maximum     = 5000.0    # temperature ceiling on solver

    module  = "dummy"           # Which atmosphere module to use

    [atmos_clim.dummy]
        gamma = 0.05

[escape]

    reservoir = "outgas"  # Escaping reservoir: "bulk", "outgas", "pxuv".
    module = "none"     # Which escape module to use
    [escape.dummy]
        rate        = 0.0           # Bulk unfractionated escape rate [kg s-1]

[interior]
    grain_size      = 0.1   # crystal settling grain size [m]
    F_initial       = 1e3   # Initial heat flux guess [W m-2]
    radiogenic_heat = false  # enable radiogenic heat production
    tidal_heat      = true  # enable tidal heat production
    rheo_phi_loc    = 0.3    # Centre of rheological transition
    rheo_phi_wid    = 0.15   # Width of rheological transition

    module = "aragog"   # Which interior module to use

    [interior.spider]
        num_levels      = 150       # Number of SPIDER grid levels
        mixing_length   = 2         # Mixing length parameterization
        tolerance       = 1.0e-8    # absolute solver tolerance
        tolerance_rel   = 1.0e-8    # relative solver tolerance
        solver_type     = "bdf"     # SUNDIALS solver method
        tsurf_atol      = 20.0      # tsurf_poststep_change
        tsurf_rtol      = 0.02      # tsurf_poststep_change_frac
        ini_entropy     = 2900.0    # Surface entropy conditions [J K-1 kg-1]
        ini_dsdr        = -4.698e-6 # Interior entropy gradient [J K-1 kg-1 m-1]

    [interior.aragog]
        num_levels                      = 70       # Number of Aragog grid levels
        tolerance                       = 5.0e-7   # solver tolerance
        ini_tmagma                      = 2800.0   # Initial magma surface temperature [K]
        tsurf_poststep_change           = 50       # threshold of maximum change on surface temperature, compares current and first Tsurf


[outgas]
    fO2_shift_IW    = 0         # log10(Î”IW), atmosphere/interior boundary oxidation state
    module = "calliope"         # Which outgassing module to use

    [outgas.calliope]
        include_H2O  = true     # Include H2O compound
        include_CO2  = true     # Include CO2 compound
        include_N2   = true     # Include N2 compound
        include_S2   = true     # Include S2 compound
        include_SO2  = true     # Include SO2 compound
        include_H2S  = true     # Include H2S compound
        include_NH3  = true     # Include NH3 compound
        include_H2   = true     # Include H2 compound
        include_CH4  = true     # Include CH4 compound
        include_CO   = true     # Include CO compound
        T_floor      = 700.0    # Temperature floor applied to outgassing calculation [K].

[delivery]

    # Radionuclide parameters
    radio_tref = 4.55   # Reference age for concentrations [Gyr]
    radio_K    = 310.0  # ppmw of potassium (all isotopes)
    radio_U    = 0.031  # ppmw of uranium (all isotopes)
    radio_Th   = 0.124  # ppmw of thorium (all isotopes)

    # Which initial inventory to use?
    initial = 'elements'        # "elements" | "volatiles"

    # No module for accretion as of yet
    module = "none"

    # Set initial volatile inventory by planetary element abundances
    [delivery.elements]
        H_oceans    = 3.0       # Hydrogen inventory in units of equivalent Earth oceans
        #H_ppmw      = 109.0     # Hydrogen inventory in ppmw relative to mantle mass

        CH_ratio    = 1.0       # C/H mass ratio in mantle/atmosphere system
        # C_ppmw      = 0.0       # Carbon inventory in ppmw relative to mantle mass

        NH_ratio    = 0.5       # N/H mass ratio in mantle/atmosphere system
        # N_ppmw      = 0.5      # Nitrogen inventory in ppmw relative to mantle mass

        SH_ratio    = 2.0       # S/H mass ratio in mantle/atmosphere system
        # S_ppmw      = 2.0     # Sulfur inventory in ppmw relative to mantle mass

[observe]
    synthesis = "none"

[atmos_chem]
    module = "none"
