#!/usr/bin/env python
"""Generate per-run configs for the super-Earth structure-evolution grid.

Each run config is base.toml with a small set of overrides applied. Run configs
are written next to this file as ``<run_name>.toml``. Regenerate with::

    python input/superearth_grid/generate.py

The output folder for each run (``params.out.path``) is set to the run name, so
results land in ``output/<run_name>/``.
"""

from __future__ import annotations

import copy
from pathlib import Path

import toml

HERE = Path(__file__).resolve().parent
BASE = toml.load(HERE / 'base.toml')

# 1 M_earth fiducial volatile inventory [kg].
H1, C1, N1, S1 = 4.70e20, 2.73e20, 5.0e18, 5.0e19


# T2 mass-scaled-linear budgets: every element scales linearly with planet mass.
def t2_budget(mass: float) -> dict:
    return {
        'H_budget': H1 * mass,
        'C_budget': C1 * mass,
        'N_budget': N1 * mass,
        'S_budget': S1 * mass,
    }


# Static structure: solve once at init, never re-solve. update_interval=0 is the
# airtight switch (hard short-circuit before any trigger is read); the deltas are
# bounded to (0,1) by the schema, so they are set maximally insensitive.
STATIC_FREEZE = {
    'update_interval': 0,
    'update_dphi_abs': 0.999,
    'update_dtmagma_frac': 0.999,
    'update_dw_comp_abs': 0.999,
    'update_stale_ceiling': 0,
}

HEADER = (
    '# Generated by input/superearth_grid/generate.py from base.toml.\n'
    '# Do not edit by hand; edit base.toml or generate.py and regenerate.\n\n'
)


def set_in(cfg: dict, dotted: str, value):
    """Set a nested key like 'planet.elements.H_budget' in a config dict."""
    keys = dotted.split('.')
    node = cfg
    for k in keys[:-1]:
        node = node[k]
    node[keys[-1]] = value


def make_run(name: str, overrides: dict) -> dict:
    """Deep-copy base, apply dotted overrides, set the output folder name."""
    cfg = copy.deepcopy(BASE)
    set_in(cfg, 'params.out.path', name)
    for dotted, value in overrides.items():
        set_in(cfg, dotted, value)
    return cfg


def write_run(name: str, cfg: dict) -> Path:
    path = HERE / f'{name}.toml'
    path.write_text(HEADER + toml.dumps(cfg))
    return path


def build_S1() -> list[str]:
    """S1 SHRINKING: mass {1,3,5,10} x structure {dynamic, static}, T2, IW+4, Sun 1 AU."""
    names = []
    for mass in (1, 3, 5, 10):
        budget = {f'planet.elements.{k}': v for k, v in t2_budget(mass).items()}
        for struct in ('dyn', 'stat'):
            name = f'S1_m{mass}_{struct}_IW4'
            ov = {'planet.mass_tot': float(mass), **budget}
            # Super-Earth masses need finer radial resolution to close the
            # core/mantle mass split under 2% (Earth-mass closes at 150).
            if mass > 1:
                ov['interior_struct.zalmoxis.num_levels'] = 300
            if struct == 'stat':
                ov.update(
                    {f'interior_struct.zalmoxis.{k}': v for k, v in STATIC_FREEZE.items()}
                )
            write_run(name, make_run(name, ov))
            names.append(name)
    return names


# --- S2 REDOX axis (results 4.3) ---------------------------------------------
# Vary only the oxygen-fugacity treatment; hold the 5 M_earth dynamic-structure
# fiducial fixed. Every S2 run is the validated per-run config with only the fO2
# block changed, so the redox grid inherits the exact structure/energetics
# numerics certified on the structure grid. Templating from the validated config
# (not base.toml) is deliberate: it guarantees byte-for-byte inheritance of the
# fiducial.
S2_TEMPLATE = HERE / 'S1_m5_dyn_IW4_sc2.toml'

# Coarse-first IW ladder. The 7 even points resolve results 4.3 fastest; the 6
# odd in-between points complete the 13-level set later with no rework (same
# names, same build path), so expanding to the full grid is a one-line swap.
IW_COARSE = (-6, -4, -2, 0, 2, 4, 6)
IW_INFILL = (-5, -3, -1, 1, 3, 5)
IW_FULL = tuple(sorted(IW_COARSE + IW_INFILL))


def _iw_tag(shift: int) -> str:
    """Filename-safe IW tag: -6 -> 'IWm6', 0 -> 'IW0', +4 -> 'IWp4'."""
    if shift > 0:
        return f'IWp{shift}'
    if shift < 0:
        return f'IWm{abs(shift)}'
    return 'IW0'


def s2_fixed_name(shift: int) -> str:
    """Run/output name for the fixed-fugacity twin at a given IW offset."""
    return f'S2_m5_{_iw_tag(int(shift))}_fixed'


def s2_oxauth_name(shift: int) -> str:
    """Run/output name for the oxygen-authoritative twin at a given IW offset."""
    return f'S2_m5_{_iw_tag(int(shift))}_oxauth'


def _s2_run(name: str, overrides: dict) -> dict:
    """Load the validated S2 template and apply only the fO2-block overrides."""
    cfg = toml.load(S2_TEMPLATE)
    set_in(cfg, 'params.out.path', name)
    for dotted, value in overrides.items():
        set_in(cfg, dotted, value)
    return cfg


def build_S2_fixed(shifts=IW_COARSE) -> list[str]:
    """Fixed-fugacity twins: fO2 buffered at each IW offset; O from chemistry.

    The oxidation state is imposed as a boundary condition. O_mode stays
    'ic_chemistry', so the total O at the molten IC is whatever the fO2-buffered
    atmodeller equilibrium produces (read back later from runtime_helpfile.csv
    'O_kg_total' to seed the oxygen-authoritative twin).
    """
    names = []
    for shift in shifts:
        name = s2_fixed_name(shift)
        cfg = _s2_run(
            name,
            {
                'planet.fO2_source': 'user_constant',
                'outgas.fO2_shift_IW': int(shift),
                'planet.elements.O_mode': 'ic_chemistry',
                'planet.elements.O_budget': 0.0,
            },
        )
        write_run(name, cfg)
        names.append(name)
    return names


def build_S2_oxauth(o_budgets: dict) -> list[str]:
    """Oxygen-authoritative twins: total O conserved at the fixed twin's t=0 O.

    Parameters
    ----------
    o_budgets : dict
        Maps IW shift (int) -> total O [kg], read from the fixed twin's t=0
        molten-IC atmodeller equilibrium ('O_kg_total', first data row of
        runtime_helpfile.csv). O becomes an authoritative conserved element
        alongside H/C/N/S; the IW offset is retained for pairing only, since
        under fO2_source='from_O_budget' it is a derived diagnostic rather than
        an input.
    """
    names = []
    for shift, o_kg in sorted(o_budgets.items()):
        name = s2_oxauth_name(int(shift))
        cfg = _s2_run(
            name,
            {
                'planet.fO2_source': 'from_O_budget',
                'outgas.fO2_shift_IW': int(shift),
                'planet.elements.O_mode': 'kg',
                'planet.elements.O_budget': float(o_kg),
            },
        )
        write_run(name, cfg)
        names.append(name)
    return names


# --- Volatile-inventory treatments (S3 axis, results 4.4) -------------------
# Four treatments describe how the volatile budget scales with planet mass,
# anchored on the 1 M_earth fiducial inventory (H1/C1/N1/S1).
#   T1 fixed-absolute : element mass constant -> volatile fraction ~ M^-1.
#   T2 mass-scaled    : every element ~ M -> constant fraction. == t2_budget,
#                       which is the S1 grid; reuse those runs, do not re-run.
#   T3 hydrogen-rich  : H grows steeply, C/N/S ~ M (sub-Neptune envelope).
#   T4 volatile-rich  : every element ~ M^2.5 (water-world).
#
# PROVISIONAL exponents flagged for confirmation before launch:
#   T3_H_EXPONENT : the H-scaling exponent. M^3 puts the H mass fraction at
#       ~0.8 % at 10 M_earth, matching the stated ~1 % H/He sub-Neptune target;
#       M^2 gives only ~0.08 %. M^3 is the default here pending sign-off.
#   T4_EXPONENT : 2.5 puts the total volatile fraction at ~0.4 % at 10 M_earth,
#       matching the stated water-world target.
T3_H_EXPONENT = 3.0
T4_EXPONENT = 2.5


def t1_budget(mass: float) -> dict:
    """Fixed-absolute volatiles: every element held at its 1 M_earth value."""
    return {'H_budget': H1, 'C_budget': C1, 'N_budget': N1, 'S_budget': S1}


def t3_budget(mass: float) -> dict:
    """Hydrogen-enriched: H ~ M**T3_H_EXPONENT, C/N/S ~ M."""
    return {
        'H_budget': H1 * mass**T3_H_EXPONENT,
        'C_budget': C1 * mass,
        'N_budget': N1 * mass,
        'S_budget': S1 * mass,
    }


def t4_budget(mass: float) -> dict:
    """Volatile-rich: every element ~ M**T4_EXPONENT."""
    return {
        'H_budget': H1 * mass**T4_EXPONENT,
        'C_budget': C1 * mass**T4_EXPONENT,
        'N_budget': N1 * mass**T4_EXPONENT,
        'S_budget': S1 * mass**T4_EXPONENT,
    }


VOLATILE_TREATMENTS = {'T1': t1_budget, 'T3': t3_budget, 'T4': t4_budget}


def _dynamic_mass_overrides(mass: int) -> dict:
    """Per-mass dynamic-structure overrides matching build_S1's dynamic twin.

    Reproduces the resolution rule build_S1 applies (num_levels=300 above
    1 M_earth, base default otherwise), so an Sx run at mass M differs from its
    S1 T2 twin only in the fields the axis varies, never in structure
    resolution.
    """
    ov = {'planet.mass_tot': float(mass)}
    if mass > 1:
        ov['interior_struct.zalmoxis.num_levels'] = 300
    return ov


# --- S3 VOLATILE-INVENTORY axis (results 4.4) --------------------------------
# At 1 M_earth all four treatments collapse to the same fiducial inventory, so
# the 1 M_earth cell for T1/T3/T4 is identical to S1_m1_dyn_IW4 (the T2 run);
# it is omitted here and reused from S1. T2 at every mass is the S1 grid.
S3_TREATMENTS = ('T1', 'T3', 'T4')
S3_MASSES = (3, 5, 10)


def _s3_cfg(treatment: str, mass: int, extra: dict | None = None) -> dict:
    """Build one S3-style config (base + per-mass structure + treatment budget).

    Templated from base.toml on the same path as build_S1 so the non-volatile
    state matches the S1 T2 twin at the same mass exactly; only the volatile
    budget (and any ``extra`` overrides, e.g. the S4 real-gas EOS) differ.
    """
    name = _s3_name(treatment, mass)
    ov = _dynamic_mass_overrides(mass)
    ov.update(
        {f'planet.elements.{k}': v for k, v in VOLATILE_TREATMENTS[treatment](mass).items()}
    )
    if extra:
        ov.update(extra)
    return make_run(name, ov)


def _s3_name(treatment: str, mass: int) -> str:
    return f'S3_{treatment}_m{mass}'


def build_S3(treatments=S3_TREATMENTS, masses=S3_MASSES) -> list[str]:
    """Volatile-treatment x mass grid (T1/T3/T4 only; T2 == S1, mass=1 == S1_m1)."""
    names = []
    for treatment in treatments:
        for mass in masses:
            name = _s3_name(treatment, mass)
            write_run(name, _s3_cfg(treatment, mass))
            names.append(name)
    return names


# --- S4 REAL-GAS vs IDEAL-GAS check (results 4.4) ----------------------------
# Real-gas twins of the two highest-pressure S3 cells (T3 and T4 at 10 M_earth).
# Only the atmodeller outgassing-chemistry EOS is switched from ideal gas to
# compensated Redlich-Kwong (CORK; Holland & Powell). 'CORK' is atmodeller's
# name for the compensated Redlich-Kwong formulation. AGNI's climate EOS stays
# at the grid default (ideal), so the comparison isolates the outgassing-EOS
# correction as a bounded validity check, not a production-mode change.
#
# LAUNCH CAVEAT: the hot fully-molten initial condition sits above the CORK
# calibration range, so real gas enabled from t=0 can fail to converge in
# atmodeller (see base.toml). Verify convergence on the fixed code before
# launch; this config is a draft.
S4_EOS = {
    'outgas.atmodeller.eos_H2O': 'H2O_cork_holland98',
    'outgas.atmodeller.eos_CO2': 'CO2_cork_holland98',
    'outgas.atmodeller.eos_H2': 'H2_cork_cs_holland91',
}
S4_CELLS = (('T3', 10), ('T4', 10))


def build_S4(cells=S4_CELLS) -> list[str]:
    """Compensated-Redlich-Kwong atmodeller twins of the highest-pressure cells."""
    names = []
    for treatment, mass in cells:
        name = f'S4_{treatment}_m{mass}_realgas'
        cfg = _s3_cfg(treatment, mass, extra=S4_EOS)
        set_in(cfg, 'params.out.path', name)
        write_run(name, cfg)
        names.append(name)
    return names


# --- S5/S6 axes template from the validated 5 M_earth fiducial ---------------
# S5 (host star) and S6 (structural robustness) hold mass at 5 M_earth, so they
# inherit the validated fiducial byte-for-byte (as S2 does) and override only
# the axis fields. S3/S4 cannot, because they vary mass.
FIDUCIAL = HERE / 'S1_m5_dyn_IW4_sc2.toml'


def _fiducial_run(name: str, overrides: dict) -> dict:
    """Load the validated 5 M_earth fiducial and apply only the axis overrides."""
    cfg = toml.load(FIDUCIAL)
    set_in(cfg, 'params.out.path', name)
    for dotted, value in overrides.items():
        set_in(cfg, dotted, value)
    return cfg


def _mdwarf_overrides() -> dict:
    """Switch the host to a 0.2 M_sun M dwarf with a PHOENIX synthetic spectrum.

    PHOENIX needs metallicity and alpha-enhancement (solar values here) and does
    not use star_name; mors clips the 0.2 M_sun mass into its 0.1-1.25 range and
    derives Teff/log g/radius from the spada tracks.
    """
    return {
        'star.mass': 0.2,
        'star.mors.spectrum_source': 'phoenix',
        'star.mors.star_name': 'none',
        'star.mors.phoenix_FeH': 0.0,
        'star.mors.phoenix_alpha': 0.0,
    }


def _axis_tag(au: float) -> str:
    """Filename-safe semimajor-axis tag: 0.1 -> 'a0p1', 0.3 -> 'a0p3'."""
    return 'a' + ('%g' % au).replace('.', 'p')


# --- S5 HOST STAR + irradiation axis (results 4.5) ---------------------------
# {Sun (solar spectrum), 0.2 M_sun M dwarf (PHOENIX)} x {0.1, 0.3} AU. Sun at
# 1 AU is the fiducial and is reused, so this builds 4 new runs.
S5_HOSTS = {'sun': dict, 'mdwarf': _mdwarf_overrides}
S5_AXES = (0.1, 0.3)


def build_S5(hosts=('sun', 'mdwarf'), axes=S5_AXES) -> list[str]:
    """Host-star x semimajor-axis grid at 5 M_earth, fiducial volatiles/redox."""
    names = []
    for host in hosts:
        host_ov = S5_HOSTS[host]()
        for au in axes:
            name = f'S5_{host}_{_axis_tag(au)}'
            write_run(name, _fiducial_run(name, {'orbit.semimajoraxis': float(au), **host_ov}))
            names.append(name)
    return names


# --- S6 STRUCTURAL-ROBUSTNESS axis (results 4.5) -----------------------------
# Core-mass fraction, initial super-liquidus offset, and tidal heating, each
# perturbing one field of the 5 M_earth fiducial.
#
# PROVISIONAL values flagged for confirmation before launch:
#   S6_DELTA_T_HOT/COLD : the super-liquidus offset bracketing the fiducial
#       500 K. Both keep a fully molten start; the hot value must still be
#       reachable within the EOS table at 5 M_earth (the IC solve raises if not).
#   S6_TIDAL_ECC : eccentricity for the tidal-on run. Eccentricity tides vanish
#       at the fiducial e=0, so a non-zero value is required for lovepy to
#       deposit heat into the interior energy balance; 0.1 sets a moderate
#       forcing at the closest-in M-dwarf cell.
#
# DEFERRED: the core-thermal-reservoir run. The knob is
# interior_struct.core_heatcap (and core_density), currently 'self'
# (self-consistent). Perturbing it meaningfully needs the fiducial's
# self-consistent baseline read back from a run, and the core energy budget is
# exactly what dev4's T_cmb / energy-closure campaign is revising, so this run
# is held until that fix lands.
S6_CMFS = (0.2, 0.5, 0.7)
S6_DELTA_T_HOT = 900.0
S6_DELTA_T_COLD = 100.0
S6_TIDAL_ECC = 0.1


def _cmf_tag(cmf: float) -> str:
    return 'cmf' + ('%g' % cmf).replace('.', 'p')


def build_S6() -> list[str]:
    """Core-mass-fraction, initial-thermal-budget, and tidal robustness runs."""
    names = []
    for cmf in S6_CMFS:
        name = f'S6_{_cmf_tag(cmf)}'
        write_run(name, _fiducial_run(name, {'interior_struct.core_frac': float(cmf)}))
        names.append(name)
    for tag, dts in (('hot', S6_DELTA_T_HOT), ('cold', S6_DELTA_T_COLD)):
        name = f'S6_dTsuper_{tag}'
        write_run(name, _fiducial_run(name, {'planet.delta_T_super': float(dts)}))
        names.append(name)
    # Tidal heating on at the closest-in M-dwarf cell (ties to S5 mdwarf 0.1 AU).
    # heat_tidal must be true for the interior to receive the lovepy power;
    # lovepy + a non-zero eccentricity alone compute it diagnostically but
    # deposit nothing while heat_tidal stays at its schema default (false).
    name = 'S6_tidal_on'
    ov = {
        'orbit.module': 'lovepy',
        'orbit.eccentricity': S6_TIDAL_ECC,
        'orbit.semimajoraxis': 0.1,
        'interior_energetics.heat_tidal': True,
        **_mdwarf_overrides(),
    }
    write_run(name, _fiducial_run(name, ov))
    names.append(name)
    return names


def write_list(list_name: str, names: list[str]) -> Path:
    """Write a SLURM-array list: one ``input/superearth_grid/<name>.toml`` per line."""
    path = HERE / list_name
    rel = 'input/superearth_grid'
    path.write_text(''.join(f'{rel}/{n}.toml\n' for n in names))
    return path


if __name__ == '__main__':
    # S1 is generated by its own driver (already launched) and S2 needs the
    # runtime O-budget handshake, so this entry point regenerates the S3-S6
    # lanes: deterministic, no runtime input.
    for label, builder, list_name in (
        ('S3', build_S3, 'S3_list.txt'),
        ('S4', build_S4, 'S4_list.txt'),
        ('S5', build_S5, 'S5_list.txt'),
        ('S6', build_S6, 'S6_list.txt'),
    ):
        written = builder()
        write_list(list_name, written)
        print(f'{label}: wrote {len(written)} configs + {list_name}')
        for n in written:
            print('  ', n)
