version = "2.0"
author = "Harrison Nicholls, Tim Lichtenberg, Mariana Sastre"

[params]
resume = false
offline = false
[params.out]
path = "all_options"
logging = "INFO"
plot_mod = 1
plot_fmt = "png"
write_mod = 5

[params.dt]
starspec = 1000000000.0
starinst = 10.0
method = "adaptive"
minimum = 10000.0
minimum_rel = 1e-05
maximum = 10000000.0
initial = 30.0

[params.dt.proportional]
propconst = 52.0

[params.dt.adaptive]
atol = 0.02
rtol = 0.1

[params.stop]
strict = false
[params.stop.iters]
enabled = true
minimum = 5
maximum = 9000

[params.stop.time]
enabled = true
maximum = 4567000000.0
minimum = 1000.0

[params.stop.solid]
phi_crit = 0.01
enabled = true

[params.stop.radeqm]
enabled = true
atol = 0.2
rtol = 0.001

[params.stop.escape]
enabled = true
p_stop = 5.0

[star]
module = "mors"
mass = 1.0
age_ini = 0.1

[star.mors]
age_now = 4.567
spec = "stellar_spectra/Named/sun.txt"
rot_pcntle = 50.0
rot_period = "none"
tracks = "spada"

[star.dummy]
radius = 1.0
Teff = 5772.0

[orbit]
module = "none"
semimajoraxis = 1.0
eccentricity = 0.0
zenith_angle = 48.19
s0_factor = 0.375

[orbit.dummy]
H_tide = 1e-07
Phi_tide = "<0.3"

[orbit.lovepy]
visc_thresh = 1000000000.0

[struct]
corefrac = 0.55
mass_tot = "none"
radius_int = 1.0
core_density = 10738.33
core_heatcap = 880.0

[atmos_clim]
module = "agni"
surf_state = "fixed"
prevent_warming = true
surface_d = 0.01
surface_k = 2.0
cloud_enabled = false
cloud_alpha = 0.0
surf_greyalbedo = 0.1
albedo_pl = 0.0
rayleigh = false
tmp_minimum = 0.5
tmp_maximum = 5000.0

[atmos_clim.agni]
spectral_group = "Honeyside"
spectral_bands = "48"
p_top = 1e-05
surf_material = "greybody"
num_levels = 40
chemistry = "none"
solve_energy = false
solution_atol = 0.001
solution_rtol = 0.02
overlap_method = "ee"
condensation = true
real_gas = true

[atmos_clim.janus]
spectral_group = "Honeyside"
spectral_bands = "48"
p_top = 1e-06
p_obs = 0.001
F_atm_bc = 0
num_levels = 40
tropopause = "none"
overlap_method = "ee"

[atmos_clim.dummy]
gamma = 0.01

[escape]
module = "zephyrus"
reservoir = "outgas"

[escape.zephyrus]
Pxuv = 5e-05
efficiency = 0.1
tidal = false

[escape.dummy]
rate = 0.0

[interior]
module = "spider"
radiogenic_heat = false
tidal_heat = false
grain_size = 0.1
F_initial = 1000.0
rheo_phi_loc = 0.3
rheo_phi_wid = 0.15
bulk_modulus = 260000000000.0

[interior.spider]
ini_entropy = 2900.0
ini_dsdr = -4.698e-06
num_levels = 150
mixing_length = 2
tolerance = 1e-08
tolerance_rel = 1e-08
solver_type = "bdf"
tsurf_atol = 20.0
tsurf_rtol = 0.02

[interior.aragog]
logging = "ERROR"
ini_tmagma = 3000.0
num_levels = 100
tolerance = 1e-07

[interior.dummy]
ini_tmagma = 3500.0

[outgas]
fO2_shift_IW = 4.0
module = "calliope"

[outgas.calliope]
T_floor = 700.0
include_H2O = true
include_CO2 = true
include_N2 = true
include_S2 = true
include_SO2 = true
include_H2S = true
include_NH3 = true
include_H2 = true
include_CH4 = true
include_CO = true

[outgas.atmodeller]
some_parameter = "some_value"

[delivery]
module = "none"
initial = "elements"
radio_tref = 4.55
radio_K = 310.0
radio_U = 0.031
radio_Th = 0.124

[delivery.elements]
H_oceans = 5.0
H_ppmw = 0.0
CH_ratio = 1.0
C_ppmw = 0.0
NH_ratio = 0.5
N_ppmw = 0.0
SH_ratio = 2.0
S_ppmw = 0.0

[delivery.volatiles]
H2O = 20.0
CO2 = 30.0
N2 = 0.0
S2 = 0.0
SO2 = 0.0
H2S = 0.0
NH3 = 0.0
H2 = 0.0
CH4 = 0.0
CO = 0.0

[observe]
synthesis = "none"
