import os
import numpy as np

spec_file_name = 'sp_example'

# Remove junk files generated by previous runs
os.system('rm -rf write_spec_file')
os.system('rm -rf ' + spec_file_name)
os.system('rm -rf ' + spec_file_name + '_k')
os.system('rm -rf *_lbl')
os.system('rm -rf *_lbl.nc')
os.system('rm -rf *_m')
os.system('rm -rf *_o')
os.system('rm -rf *_o.nc')
os.system('rm -rf *_l')

# Open file to produce bash script
f= open("write_spec_file","w+")

# Write skeleton spectral file using prep_spec utility
f.write('prep_spec <<EOF'+ '\n')
f.write(spec_file_name+ '\n')

# Set number of bands
f.write('10'+ '\n')
# Set number of absorbers
f.write('1'+ '\n')
# Set absorber ids (see Socrates userguide)
f.write('1'+ '\n')
# Set number of continua
f.write('0'+ '\n')
# Set number of aerosols
f.write('0'+ '\n')
# Set band units (c for inverse cm)
f.write('c'+ '\n')

# Set band edges in cm-1
bands = np.arange(0,11000,1000)
bands[0] = 1.0

# Write band edges one by one
f.write(str(bands[0])+'\n')
for band in bands[1:-1]:
	f.write(str(band)+'\n')
	f.write(str(band)+'\n')
f.write(str(bands[-1])+'\n')

# Set absorbers in each band
for band in bands[:-1]:
	f.write('1'+ '\n')

# Set continua in each band
for band in bands[:-1]:
	f.write('0'+ '\n')

# Exclude no bands
f.write('n'+ '\n')

# Close prep_spec
f.write('-1'+ '\n')
f.write('EOF'+ '\n')

#####################

# Write correlated-k coefficients using Ccorr_k utility, with suffixes:
# -F File with grid of pressure-temperature values
# -R Range of bands for the calculation (default to all)
# -c Cutoff in inverse cm for each band
# -i Frequency increment for integration in m-1
# -l Maximum absorption path in kg/m2
# -t Tolerance, i.e. maximum RMS error in correlated-k assumption
# -k Adjust for use with CKD continuum (optional)
# -s Spectral file
# +p Planckian weighting
# -lk Use lookup table for pressure/temperature scaling
# -o, -m, -L Output files
# -np Number of processors

f.write('Ccorr_k -F pt48 -D h2o_data.par -R 1 10 -c 2500.0 -i 1.0 -l 1 1.0e1 -t 1.0e-2 -s ' + spec_file_name + ' +p -lk -o h2o_o -m h2o_m -L h2o_lbl.nc -np 16'+ '\n')

# Add to spec file
f.write('prep_spec <<EOF'+ '\n')
# Select spectral file
f.write(spec_file_name+ '\n')
# Append
f.write('a'+ '\n')
# Select block 5 (absorption data)
f.write('5'+ '\n')
# Select data
f.write('h2o_o'+ '\n')

#####################
# Thermal source function is required for LW calculation
# Stellar spectrum is required for SW calculation

# They are independent so can both be present, although separate spectral files
# with more appropriate bins may be used for the LW and SW calculations

# Thermal source function
f.write('6'+ '\n')
f.write('n'+ '\n')
# Select polynomial fit
f.write('p'+ '\n')
# Temperature range in K
f.write('250 2250'+ '\n')
# Order of fitting polynomial
f.write('12'+ '\n')

# Solar spectrum
f.write('2'+ '\n')
# No filter function
f.write('n'+ '\n')
# Path to spectrum data
f.write('/Users/markhammond/Work/Projects/1D-RC-SOC/socrates/socrates_main/data/solar/kurucz_95'+ '\n')
# Assign flux outside data range to bands on edge
f.write('y'+ '\n')

# Exit
f.write('-1'+ '\n')
f.write('EOF'+ '\n')

# Close
f.close()
os.chmod('write_spec_file',0o777)

#######################

# Remove junk files
os.system('rm -rf *_l')
os.system('rm -rf *_lm')
os.system('rm -rf *_lbl.nc')
os.system('rm -rf *_map.nc')

# Run script
os.system('./write_spec_file')
