# AGNI configuration file used when coupling to PROTEUS
title = "PROTEUS base"

[planet]
    turb_coeff      = 1.0e-3
    wind_speed      = 10.0

[files]
    clean_output    = false

[execution]
    silent          = false  
    max_steps       = 150    
    max_runtime     = 700    
    continua        = true   
    aerosol         = false  
    overlap_method  = 4      
    thermo_funct    = true  
    sensible_heat   = true  
    latent_heat     = true 
    convection_type = "mlt" 
    solvers         = ["newton"]  
    dx_max          = 230.0    
    chemistry       = 0
    initial_state   = ["dry","str","1500"] 
    converge_atol   = 1.0e-2  
    converge_rtol   = 1.0e-2  


[plots]
    animate         = false
    contribution    = false
    emission        = false
    albedo          = false
    mixing_ratios   = false
