n_workers = 7

kernel = "RBF"

sim = true
max_len = 100
n_restarts = 10
n_samples = 1000

D_init_path = "data/ackley.pth"

directory = "inference/results/"

ref_config = "input/demos/dummy.toml"

[observables]
z_obs = 0.0
R_int = 6345655.0
M_planet = 5.98032e+24
transit_depth = 8.319725e-05
bond_albedo = 0.1111111
contrast_ratio = 3.7496e-10

[parameters]
struct.mass_tot = [0.5, 3.0]
struct.corefrac = [0.3, 0.9]
atmos_clim.surf_greyalbedo = [0.0, 0.51]
atmos_clim.dummy.gamma = [0.05, 0.95]
escape.dummy.rate = [0.0, 1e5]
interior.dummy.ini_tmagma = [2000, 4500]
outgas.fO2_shift_IW = [-4.0, 4.0]
delivery.radio_K = [50, 400]
delivery.elements.H_oceans = [0.5, 18]

