version = "2.0"
author = "Harrison Nicholls, Tim Lichtenberg"

[star]
mass = 1.0
radius = 1.0
Teff = 5772.0
Lbol = 1.0
omega = 50.0
age_now = 4.567
age_ini = 0.1
module = "mors"

[orbit]
semimajoraxis = 1.0
eccentricity = 0.0
zenith_angle = 48.19
s0_factor = 0.375

[struct]
mass = 1.0
radius = 1.0
corefrac = 0.55

[atmos_clim]
prevent_warming = true
surface_d = 0.01
surface_k = 2.0
cloud_enabled = false
cloud_alpha = 0.0
surf_state = "skin"
surf_albedo = 0.1
albedo_pl = 0.1
rayleigh = true
tmp_minimum = 0.5
tmp_maximum = 5000.0
module = "janus"

[escape]
module = "dummy"

[interior]
grain_size = 0.1
F_initial = 80000.0
module = "spider"

[outgas]
fO2_shift_IW = 4.0
module = "calliope"

[delivery]
initial = "volatiles"

[params.out]
path = "default"
logging = "DEBUG"
plot_mod = 1
plot_fmt = "pdf"

[params.dt]
minimum = 300.0
maximum = 30000000.0
initial = 10000.0
starspec = 1000000000.0
starinst = 100.0
method = "adaptive"

[star.mors]
tracks = "spada"
spec = "stellar_spectra/Named/sun.txt"

[atmos_clim.agni]
p_top = 1e-5
spectral_group = "Frostflow"
spectral_bands = "256"
num_levels = 250

[atmos_clim.janus]
p_top = 1e-6
spectral_group = "Frostflow"
spectral_bands = "256"
F_atm_bc = 0
num_levels = 250
tropopause = "skin"

[atmos_clim.dummy]
gamma = 0.7

[escape.zephyrus]
some_parameter = "some_value"

[escape.dummy]
rate = 0.0

[interior.spider]
num_levels = 220
mixing_length = 2
tolerance = 1e-10
tsurf_atol = 20.0
tsurf_rtol = 0.01
ini_entropy = 2600.0
ini_dsdr = -4.698e-6

[interior.aragog]
some_parameter = "some_value"

[outgas.calliope]
include_H2O = true
include_CO2 = true
include_N2 = true
include_S2 = true
include_SO2 = false
include_H2 = false
include_CH4 = false
include_CO = false

[outgas.atmodeller]
some_parameter = "some_value"

[delivery.elements]
CH_ratio = 1.0
H_oceans = 6.0
N_ppmw = 2.0
S_ppmw = 200.0

[delivery.volatiles]
H2O = 30.0
CO2 = 0.0
N2 = 0.0
S2 = 0.0
SO2 = 0.0
H2 = 0.0
CH4 = 0.0
CO = 0.0

[params.dt.proportional]
propconst = 52.0

[params.dt.adaptive]
atol = 0.02
rtol = 0.07

[params.stop.iters]
enabled = true
minimum = 3
maximum = 9000

[params.stop.time]
enabled = true
minimum = 1000.0
maximum = 4567000000.0

[params.stop.solid]
enabled = true
phi_crit = 0.005

[params.stop.radeqm]
enabled = true
F_crit = 0.2

[params.stop.steady]
enabled = true
F_crit = 0.8
dprel = 1e-9

[params.stop.escape]
enabled = true
mass_frac = 0.0003
