version = "2.0"
author = "Harrison Nicholls, Tim Lichtenberg"

[params]
resume = false
offline = false
[params.out]
path = "default"
logging = "INFO"
plot_mod = 10
plot_fmt = "png"
write_mod = 1

[params.dt]
minimum = 10.0
maximum = 300000.0
initial = 2000.0
starspec = 1000000000.0
starinst = 100.0
method = "adaptive"

[params.dt.proportional]
propconst = 52.0

[params.dt.adaptive]
atol = 0.02
rtol = 0.07

[params.stop]
strict = false

[params.stop.iters]
enabled = true
minimum = 8
maximum = 9000

[params.stop.time]
enabled = true
minimum = 1000.0
maximum = 200000000.0

[params.stop.solid]
enabled = true
phi_crit = 0.02

[params.stop.radeqm]
enabled = false
atol = 0.4
rtol = 0.03

[params.stop.escape]
enabled = true
mass_frac = 0.0003

[star]
mass = 0.273
age_ini = 0.1
module = "mors"

[star.mors]
rot_pctle = 50.0
tracks = "spada"
age_now = 4.94
spec = "stellar_spectra/Named/l-98-59.txt"

[star.dummy]
radius = 1.0
Teff = 5772.0

[orbit]
semimajoraxis = 0.02191
eccentricity = 0.167
zenith_angle = 54.74
s0_factor = 0.25
module = "none"

[orbit.dummy]
H_tide = 0.0
Phi_tide = "<0.3"

[orbit.lovepy]
visc_thresh = 1000000000.0

[struct]
set_by = "mass_tot"
mass_tot = 0.47
radius_int = 1.0
corefrac = 0.55
core_density = 10738.33
core_heatcap = 880.0

[atmos_clim]
prevent_warming = false
surface_d = 0.01
surface_k = 2.0
cloud_enabled = false
cloud_alpha = 0.0
surf_state = "fixed"
surf_greyalbedo = 0.2
albedo_pl = 0.0
rayleigh = true
tmp_minimum = 0.5
tmp_maximum = 5000.0
module = "agni"

[atmos_clim.agni]
p_top = 0.0001
spectral_group = "Dayspring"
spectral_bands = "256"
surf_material = "surface_albedos/Hammond24/lunarmarebasalt.dat"
num_levels = 60
chemistry = "none"
solve_energy = false
solution_atol = 0.03
solution_rtol = 0.09
overlap_method = "ee"
condensation = true
real_gas = true

[atmos_clim.janus]
p_top = 1e-05
p_obs = 0.001
spectral_group = "Honeyside"
spectral_bands = "256"
F_atm_bc = 0
num_levels = 90
tropopause = "none"
overlap_method = "ee"

[atmos_clim.dummy]
gamma = 0.0

[escape]
module = "zephyrus"

[escape.zephyrus]
Pxuv = 0.01
efficiency = 0.5
tidal = false

[escape.dummy]
rate = 0.0

[interior]
grain_size = 0.1
F_initial = 100000.0
radiogenic_heat = true
tidal_heat = false
rheo_phi_loc = 0.3
rheo_phi_wid = 0.15
bulk_modulus = 260000000000.0
module = "spider"

[interior.spider]
num_levels = 80
mixing_length = 2
tolerance = 1e-06
tsurf_atol = 10.0
tsurf_rtol = 0.004
ini_entropy = 3100.0
ini_dsdr = -4.698e-06

[interior.aragog]
ini_tmagma = 3200.0
num_levels = 200
tolerance = 1e-09

[interior.dummy]
ini_tmagma = 3000.0

[outgas]
fO2_shift_IW = 0.0
module = "calliope"

[outgas.calliope]
T_floor = 700.0
include_H2O = true
include_CO2 = true
include_N2 = true
include_S2 = true
include_SO2 = true
include_H2 = true
include_CH4 = true
include_CO = true

[outgas.atmodeller]
some_parameter = "some_value"

[delivery]
initial = "elements"
module = "none"
radio_tref = 4.55
radio_U = 0.031
radio_K = 310.0
radio_Th = 0.124

[delivery.elements]
H_oceans = 0.0
H_ppmw = 109.0
CH_ratio = 1.0
C_ppmw = 0.0
NH_ratio = 0.018
N_ppmw = 0.0
SH_ratio = 2.16
S_ppmw = 0.0

[delivery.volatiles]
H2O = 0.0
CO2 = 0.0
N2 = 0.0
S2 = 0.0
SO2 = 0.0
H2 = 0.0
CH4 = 0.0
CO = 0.0
