#!/usr/bin/env python
"""Generate SPIDER S(P) phase boundary files from T(P) melting curves.

SPIDER uses entropy-based phase boundaries S(P), while Zalmoxis and Aragog use
temperature-based T(P) curves. Both file types live in the same melting curves
folder under FWL_DATA/interior_lookup_tables/Melting_curves/<melting_dir>/:

    solidus_P-T.dat      — T(P) format, used by Zalmoxis/Aragog
    liquidus_P-T.dat     — T(P) format, used by Zalmoxis/Aragog
    solidus_P-S.dat  — S(P) format, used by SPIDER (generated by this tool)
    liquidus_P-S.dat — S(P) format, used by SPIDER (generated by this tool)

The conversion inverts SPIDER's T(P,S) lookup tables to find S(P) such that
T_table(P, S) = T_target(P), using Brent's method at each pressure.

Usage
-----
    python tools/generate_spider_phase_boundaries.py
    python tools/generate_spider_phase_boundaries.py --melting-dir Monteux-600
    python tools/generate_spider_phase_boundaries.py --melting-dir Wolf_Bower+2018

Requirements
------------
    - FWL_DATA environment variable set
    - SPIDER P-S lookup tables in FWL_DATA/interior_lookup_tables/EOS/dynamic/<eos_dir>/P-S/
      (falls back to <PROTEUS>/SPIDER/lookup_data/<eos_dir>/)
    - T(P) melting curves (solidus_P-T.dat, liquidus_P-T.dat) in the melting_dir folder
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import numpy as np
from scipy.interpolate import RegularGridInterpolator, interp1d
from scipy.optimize import brentq

PROTEUS_ROOT = Path(__file__).resolve().parents[1]
SPIDER_ROOT = PROTEUS_ROOT / 'SPIDER'
FWL_DATA = Path(os.environ.get('FWL_DATA', ''))
MELTING_CURVES_BASE = FWL_DATA / 'interior_lookup_tables' / 'Melting_curves'
EOS_DYNAMIC_BASE = FWL_DATA / 'interior_lookup_tables' / 'EOS' / 'dynamic'


# -- SPIDER lookup table loader ---------------------------------------------


def load_spider_2d(filepath: Path) -> dict:
    """Load a SPIDER 2D lookup file (P, S) -> quantity.

    Parameters
    ----------
    filepath : Path
        Path to the .dat file.

    Returns
    -------
    dict
        Keys: P_nd, S_nd, values (2D: nS x nP), P_scale, S_scale, nP, nS.
    """
    with open(filepath) as f:
        lines = f.readlines()

    dims = lines[0].strip().lstrip('#').split()
    nP = int(dims[1])
    nS = int(dims[2])

    scales = lines[4].strip().lstrip('#').split()
    P_scale = float(scales[0])
    S_scale = float(scales[1])

    data = np.loadtxt(filepath, comments='#')
    assert len(data) == nP * nS, f'Expected {nP * nS} rows, got {len(data)}'

    # Layout: S is slow (outer), P is fast (inner)
    P_1d = data[:nP, 0]
    S_1d = data[::nP, 1][:nS]
    values = data[:, 2].reshape(nS, nP)

    return {
        'P_nd': P_1d,
        'S_nd': S_1d,
        'values': values,
        'P_scale': P_scale,
        'S_scale': S_scale,
        'nP': nP,
        'nS': nS,
    }


# -- Inversion ---------------------------------------------------------------


def invert_T_to_S(
    T_table: dict,
    P_target_GPa: np.ndarray,
    T_target_func: callable,
) -> np.ndarray:
    """Find S(P) such that T(P, S) = T_target(P) by inverting the lookup table.

    At each pressure, uses Brent's method to solve T(P, S) - T_target = 0
    for S, where T(P, S) is linearly interpolated from the lookup table.

    Parameters
    ----------
    T_table : dict
        Output of load_spider_2d for a temperature table.
    P_target_GPa : np.ndarray
        Pressure grid [GPa] at which to evaluate.
    T_target_func : callable
        Function P [Pa] -> T [K] for the target melting curve.

    Returns
    -------
    S_result : np.ndarray
        Entropy [J/kg/K] at each pressure. NaN where inversion fails.
    """
    P_SI = T_table['P_nd'] * T_table['P_scale']
    S_SI = T_table['S_nd'] * T_table['S_scale']

    interp = RegularGridInterpolator(
        (S_SI, P_SI),
        T_table['values'],
        bounds_error=False,
        fill_value=np.nan,
    )

    S_min, S_max = S_SI[0], S_SI[-1]
    if S_min > S_max:
        S_min, S_max = S_max, S_min

    S_result = np.full(len(P_target_GPa), np.nan)

    for i, P_GPa in enumerate(P_target_GPa):
        P_Pa = P_GPa * 1e9
        T_target = T_target_func(P_Pa)

        if np.isnan(T_target):
            continue

        def residual(S):
            T_eval = interp((S, P_Pa))
            if np.isnan(T_eval):
                return np.nan
            return float(T_eval) - T_target

        try:
            f_lo = residual(S_min)
            f_hi = residual(S_max)
        except Exception:
            continue

        if np.isnan(f_lo) or np.isnan(f_hi):
            continue
        if f_lo * f_hi > 0:
            continue

        try:
            S_sol = brentq(residual, S_min, S_max, xtol=1e-2, rtol=1e-10)
            S_result[i] = S_sol
        except (ValueError, RuntimeError):
            continue

    return S_result


# -- File writer --------------------------------------------------------------


def write_phase_boundary(
    filepath: Path,
    P_GPa: np.ndarray,
    S_SI: np.ndarray,
    P_scale: float = 1e9,
    S_scale: float = 4824266.84604467,
):
    """Write a SPIDER-format 1D phase boundary file.

    Parameters
    ----------
    filepath : Path
        Output path.
    P_GPa : np.ndarray
        Pressure grid [GPa].
    S_SI : np.ndarray
        Entropy values [J/kg/K].
    P_scale : float
        Pressure scaling factor [Pa].
    S_scale : float
        Entropy scaling factor [J/kg/K].
    """
    valid = ~np.isnan(S_SI)
    P_out = P_GPa[valid]
    S_out = S_SI[valid]

    N = len(P_out)
    P_nd = P_out * 1e9 / P_scale
    S_nd = S_out / S_scale

    with open(filepath, 'w') as f:
        f.write(f'# 5 {N}\n')
        f.write('# Pressure [nondim], Entropy [nondim]\n')
        f.write('# column * scaling factor = SI units: Pressure [Pa], Entropy [J/kg/K]\n')
        f.write('# scaling factors (constant) for each column given on line below\n')
        f.write(f'# {P_scale} {S_scale}\n')
        for p, s in zip(P_nd, S_nd):
            f.write(f'{p:.18e} {s:.18e}\n')

    print(f'  Wrote {N} points to {filepath}')


# -- Main ---------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(
        description='Generate SPIDER S(P) phase boundaries from T(P) melting curves.',
    )
    parser.add_argument(
        '--melting-dir',
        default='Monteux-600',
        help='Name of melting curves folder in FWL_DATA (default: Monteux-600)',
    )
    parser.add_argument(
        '--eos-dir',
        default='WolfBower2018_MgSiO3',
        help='Name of dynamic EOS folder (default: WolfBower2018_MgSiO3)',
    )
    args = parser.parse_args()

    # Validate paths
    mc_folder = MELTING_CURVES_BASE / args.melting_dir
    if not mc_folder.is_dir():
        print(f'ERROR: Melting curves folder not found: {mc_folder}', file=sys.stderr)
        sys.exit(1)

    solidus_tp = mc_folder / 'solidus_P-T.dat'
    liquidus_tp = mc_folder / 'liquidus_P-T.dat'
    for f in (solidus_tp, liquidus_tp):
        if not f.is_file():
            print(f'ERROR: T(P) file not found: {f}', file=sys.stderr)
            sys.exit(1)

    # Find SPIDER P-S lookup tables: FWL_DATA first, then SPIDER local
    spider_lookup = EOS_DYNAMIC_BASE / args.eos_dir / 'P-S'
    if not spider_lookup.is_dir():
        spider_lookup = SPIDER_ROOT / 'lookup_data' / '1TPa-dK09-elec-free'
    if not spider_lookup.is_dir():
        print(f'ERROR: SPIDER lookup directory not found: {spider_lookup}', file=sys.stderr)
        sys.exit(1)

    # Load SPIDER T(P,S) tables
    print(f'Loading SPIDER temperature lookup tables from {spider_lookup}/')
    T_solid = load_spider_2d(spider_lookup / 'temperature_solid.dat')
    T_melt = load_spider_2d(spider_lookup / 'temperature_melt.dat')

    print(f'  Solid table: {T_solid["nP"]} P x {T_solid["nS"]} S points')
    print(f'  Melt table:  {T_melt["nP"]} P x {T_melt["nS"]} S points')
    print(f'  Solid T range: {T_solid["values"].min():.0f} - {T_solid["values"].max():.0f} K')
    print(f'  Melt T range:  {T_melt["values"].min():.0f} - {T_melt["values"].max():.0f} K')

    # Load T(P) melting curves
    print(f'\nLoading T(P) curves from {mc_folder}/')
    sol_data = np.loadtxt(solidus_tp, comments='#')
    liq_data = np.loadtxt(liquidus_tp, comments='#')

    P_sol_Pa, T_sol_K = sol_data[:, 0], sol_data[:, 1]
    P_liq_Pa, T_liq_K = liq_data[:, 0], liq_data[:, 1]

    print(
        f'  Solidus:  {len(P_sol_Pa)} points, '
        f'P = {P_sol_Pa[0] / 1e9:.1f}-{P_sol_Pa[-1] / 1e9:.1f} GPa, '
        f'T = {T_sol_K[0]:.0f}-{T_sol_K[-1]:.0f} K'
    )
    print(
        f'  Liquidus: {len(P_liq_Pa)} points, '
        f'P = {P_liq_Pa[0] / 1e9:.1f}-{P_liq_Pa[-1] / 1e9:.1f} GPa, '
        f'T = {T_liq_K[0]:.0f}-{T_liq_K[-1]:.0f} K'
    )

    f_sol = interp1d(P_sol_Pa, T_sol_K, bounds_error=False, fill_value=np.nan)
    f_liq = interp1d(P_liq_Pa, T_liq_K, bounds_error=False, fill_value=np.nan)

    # Pressure grid: 0-999 GPa in 1 GPa steps
    P_grid_GPa = np.arange(0, 1000, 1.0)

    # Invert solidus: T_solid(P, S) = T_solidus(P) -> S_solidus(P)
    print('\nInverting solid T(P,S) table for solidus...')
    S_solidus = invert_T_to_S(T_solid, P_grid_GPa, f_sol)
    n_valid_sol = np.sum(~np.isnan(S_solidus))
    print(f'  Valid: {n_valid_sol}/{len(P_grid_GPa)} points')

    # Invert liquidus: T_melt(P, S) = T_liquidus(P) -> S_liquidus(P)
    print('Inverting melt T(P,S) table for liquidus...')
    S_liquidus = invert_T_to_S(T_melt, P_grid_GPa, f_liq)
    n_valid_liq = np.sum(~np.isnan(S_liquidus))
    print(f'  Valid: {n_valid_liq}/{len(P_grid_GPa)} points')

    # Write S(P) files
    print(f'\nWriting S(P) phase boundary files to {mc_folder}/')
    write_phase_boundary(mc_folder / 'solidus_P-S.dat', P_grid_GPa, S_solidus)
    write_phase_boundary(mc_folder / 'liquidus_P-S.dat', P_grid_GPa, S_liquidus)

    # Verification: round-trip T(P) comparison
    print('\nVerification: round-trip T(P) comparison...')
    P_SI_solid = T_solid['P_nd'] * T_solid['P_scale']
    S_SI_solid = T_solid['S_nd'] * T_solid['S_scale']
    P_SI_melt = T_melt['P_nd'] * T_melt['P_scale']
    S_SI_melt = T_melt['S_nd'] * T_melt['S_scale']

    interp_solid = RegularGridInterpolator(
        (S_SI_solid, P_SI_solid),
        T_solid['values'],
        bounds_error=False,
        fill_value=np.nan,
    )
    interp_melt = RegularGridInterpolator(
        (S_SI_melt, P_SI_melt),
        T_melt['values'],
        bounds_error=False,
        fill_value=np.nan,
    )

    valid_sol = ~np.isnan(S_solidus)
    valid_liq = ~np.isnan(S_liquidus)

    T_rt_sol = np.array(
        [
            interp_solid((S_solidus[i], P_grid_GPa[i] * 1e9))
            for i in range(len(P_grid_GPa))
            if valid_sol[i]
        ]
    )
    T_rt_liq = np.array(
        [
            interp_melt((S_liquidus[i], P_grid_GPa[i] * 1e9))
            for i in range(len(P_grid_GPa))
            if valid_liq[i]
        ]
    )

    T_target_sol = f_sol(P_grid_GPa[valid_sol] * 1e9)
    T_target_liq = f_liq(P_grid_GPa[valid_liq] * 1e9)

    dT_sol = np.abs(T_rt_sol - T_target_sol)
    dT_liq = np.abs(T_rt_liq - T_target_liq)

    print(f'  Solidus  |dT|: mean={np.mean(dT_sol):.3f} K, max={np.max(dT_sol):.3f} K')
    print(f'  Liquidus |dT|: mean={np.mean(dT_liq):.3f} K, max={np.max(dT_liq):.3f} K')

    print('\nDone. Files ready for SPIDER:')
    print(f'  {mc_folder / "solidus_P-S.dat"}')
    print(f'  {mc_folder / "liquidus_P-S.dat"}')


if __name__ == '__main__':
    main()
