#!/usr/bin/env python3
"""Regenerate the module dispatch map from the wrappers and the config schema.

Renders one table per physics area into ``docs/Reference/module_map.md`` (and
the sidecar ``module_map.json``): which values of ``<area>.module`` exist,
which implementation file and entry point each value routes to, and which
secondary dispatch switches operate within the area. The declared rows are
machine-verified on every run: each entry symbol must exist at top level of
its file, the option set must match the config validator exactly, and every
module-name comparison in the source must use a real option.

Usage:
    python tools/generate_module_map.py            # regenerate in place
    python tools/generate_module_map.py --check    # verify, write nothing

Exit codes:
    0  committed output is current and all parity checks pass
    1  output is stale, or a parity/verification check failed
    2  structural error (missing marker or page, unparseable source)
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

import _config_schema
import _docgen
from _docgen import REPO_ROOT

PAGE = REPO_ROOT / 'docs' / 'Reference' / 'module_map.md'
JSON_PATH = REPO_ROOT / 'docs' / 'Reference' / 'module_map.json'
SRC = REPO_ROOT / 'src' / 'proteus'
REGEN_CMD = 'python tools/generate_module_map.py'

GENERATED_NOTE = (
    '<!-- Generated by tools/generate_module_map.py; '
    'edit the wrappers and config validators, not this page -->'
)

# One block per dispatch site. ``entries`` maps every validator option to
# (implementation file relative to src/proteus, entry symbol, role). A None
# file marks a disabled-module option with no implementation. Rows are
# verified against the source on every run; see the module docstring.
DISPATCH_SITES = [
    {
        'area': 'Atmosphere climate',
        'config_path': 'atmos_clim.module',
        'wrapper': 'atmos_clim/wrapper.py',
        'entries': {
            'agni': ('atmos_clim/agni.py', 'run_agni', 'Radiative-convective solver (Julia)'),
            'janus': ('atmos_clim/janus.py', 'RunJANUS', 'Convective adiabat profile'),
            'dummy': ('atmos_clim/dummy.py', 'RunDummyAtm', 'Grey-body placeholder'),
        },
    },
    {
        'area': 'Atmospheric chemistry',
        'config_path': 'atmos_chem.module',
        'wrapper': 'atmos_chem/wrapper.py',
        'entries': {
            'vulcan': ('atmos_chem/vulcan.py', 'run_vulcan', 'Kinetics network (VULCAN)'),
            'dummy': ('atmos_chem/dummy.py', 'run_dummy_chem', 'Rainout-only placeholder'),
            None: (None, None, 'Chemistry disabled'),
        },
    },
    {
        'area': 'Atmospheric escape',
        'config_path': 'escape.module',
        'wrapper': 'escape/wrapper.py',
        'entries': {
            'zephyrus': (
                'escape/wrapper.py',
                'run_zephyrus',
                'Energy-limited escape (ZEPHYRUS)',
            ),
            'boreas': ('escape/boreas.py', 'run_boreas', 'Hydrodynamic escape (BOREAS)'),
            'dummy': ('escape/wrapper.py', 'run_dummy', 'Fixed bulk escape rate'),
            None: (None, None, 'Escape disabled; rates zeroed'),
        },
    },
    {
        'area': 'Interior energetics',
        'config_path': 'interior_energetics.module',
        'wrapper': 'interior_energetics/wrapper.py',
        'entries': {
            'spider': (
                'interior_energetics/spider.py',
                'RunSPIDER',
                'T-S formalism (C, PETSc)',
            ),
            'aragog': (
                'interior_energetics/aragog.py',
                'AragogRunner',
                'T-P formalism (Python)',
            ),
            'boundary': (
                'interior_energetics/boundary.py',
                'BoundaryRunner',
                'Boundary-layer energy balance',
            ),
            'dummy': ('interior_energetics/dummy.py', 'run_dummy_int', 'Prescribed cooling'),
        },
    },
    {
        'area': 'Interior structure',
        'config_path': 'interior_struct.module',
        'wrapper': 'interior_energetics/wrapper.py',
        'entries': {
            'zalmoxis': (
                'interior_energetics/wrapper.py',
                'determine_interior_radius_with_zalmoxis',
                'Self-consistent EOS structure (interior_struct/zalmoxis.py)',
            ),
            'spider': (
                'interior_energetics/wrapper.py',
                'determine_interior_radius',
                'Radius root-find against the energetics module',
            ),
            'dummy': (
                'interior_energetics/wrapper.py',
                'determine_interior_radius_with_dummy',
                'Two-layer analytic structure (interior_struct/dummy.py)',
            ),
            None: (None, None, 'Structure solve disabled'),
        },
    },
    {
        'area': 'Orbit and tides',
        'config_path': 'orbit.module',
        'wrapper': 'orbit/wrapper.py',
        'entries': {
            'lovepy': ('orbit/lovepy.py', 'run_lovepy', 'Multi-phase tidal heating (Julia)'),
            'dummy': ('orbit/dummy.py', 'run_dummy_orbit', 'Fixed Im(k2) tides'),
            None: (None, None, 'Tides disabled; Im(k2) set to zero'),
        },
    },
    {
        'area': 'Outgassing',
        'config_path': 'outgas.module',
        'wrapper': 'outgas/wrapper.py',
        'entries': {
            'calliope': (
                'outgas/calliope.py',
                'calc_surface_pressures',
                'fO2-buffered equilibrium (CALLIOPE)',
            ),
            'atmodeller': (
                'outgas/atmodeller.py',
                'calc_surface_pressures_atmodeller',
                'Equilibrium chemistry (atmodeller)',
            ),
            'dummy': (
                'outgas/dummy.py',
                'calc_surface_pressures_dummy',
                'Prescribed pressures',
            ),
        },
    },
    {
        'area': 'Star',
        'config_path': 'star.module',
        'wrapper': 'star/wrapper.py',
        'entries': {
            'mors': ('star/wrapper.py', 'init_star', 'Stellar evolution via the mors package'),
            'dummy': ('star/dummy.py', 'generate_spectrum', 'Black-body star'),
            None: (None, None, 'No stellar evolution'),
        },
    },
    {
        'area': 'Observations',
        'config_path': 'observe.module',
        'wrapper': 'observe/wrapper.py',
        'entries': {
            'petitRADTRANS': (
                'observe/petitRADTRANS.py',
                'transit_depth',
                'Synthetic transit and eclipse spectra',
            ),
            None: (None, None, 'Observational synthesis disabled'),
        },
    },
]

# Comparisons against values outside the validator option set that the
# tree-wide validity check must tolerate, keyed by (file, dotted path, value).
# interior_energetics/boundary.py:118 guards mantle-mass derivation on
# interior_struct.module == 'self', which no validator accepts, so the branch
# cannot fire; it is kept as-is pending a decision on the intended condition.
KNOWN_DEAD_ARMS = {
    ('src/proteus/interior_energetics/boundary.py', 'interior_struct.module', 'self'),
}

# Secondary switches that route work within an area. Each symbol is verified
# to exist at top level of its file.
SUB_DISPATCHES = [
    (
        'Outgassing',
        '`outgas.vapourise = true`',
        'outgas/lavatmos.py',
        'run_vapourisation',
        'adds rock-vapour equilibrium (LavAtmos) after the outgassing solve',
    ),
    (
        'Outgassing',
        '`outgas.h2_binodal = true`',
        'outgas/binodal.py',
        'apply_binodal_h2',
        'applies the H2-silicate binodal miscibility limit',
    ),
    (
        'Orbit and tides',
        '`orbit.evolve = true`',
        'orbit/orbit.py',
        'evolve_orbital',
        'evolves semi-major axis and eccentricity each iteration',
    ),
    (
        'Orbit and tides',
        '`orbit.satellite = true`',
        'orbit/satellite.py',
        'update_satellite',
        'evolves the satellite orbit instead of the planetary one',
    ),
    (
        'Star',
        '`star.mors.tracks`',
        'star/wrapper.py',
        'get_new_spectrum',
        'selects the Spada or Baraffe evolution tracks within MORS',
    ),
    (
        'Atmospheric chemistry',
        '`atmos_chem.when`',
        'atmos_chem/wrapper.py',
        'run_chemistry',
        "runs the network 'online' during the loop, 'offline' afterwards, or 'manually'",
    ),
]


# ---------------------------------------------------------------------------
# Source verification
# ---------------------------------------------------------------------------


def _chain_of(node) -> list[str]:
    parts: list[str] = []
    while isinstance(node, ast.Attribute):
        parts.append(node.attr)
        node = node.value
    if isinstance(node, ast.Name):
        parts.append(node.id)
    return list(reversed(parts))


def scan_compared_options(path: Path, dotted: tuple[str, str]) -> set:
    """Constants the file compares against ``config.<area>.module``.

    Covers equality and membership comparisons, ``is (not) None``, falsy
    tests, match statements, and comparisons through a simple local alias
    (``module = config.<area>.module``).
    """
    tree = ast.parse(path.read_text())
    aliases: set[str] = set()

    def is_target(node) -> bool:
        if isinstance(node, ast.Name) and node.id in aliases:
            return True
        if isinstance(node, ast.Call) and node.args:  # str(config.x.module)
            return is_target(node.args[0])
        if not isinstance(node, ast.Attribute):
            return False
        chain = _chain_of(node)
        return tuple(chain[-2:]) == dotted and 'config' in ''.join(chain[:-2])

    for node in ast.walk(tree):
        if isinstance(node, ast.Assign) and len(node.targets) == 1:
            if isinstance(node.targets[0], ast.Name) and is_target(node.value):
                aliases.add(node.targets[0].id)

    found: set = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Compare) and is_target(node.left):
            for op, comp in zip(node.ops, node.comparators):
                if isinstance(op, (ast.Eq, ast.NotEq)) and isinstance(comp, ast.Constant):
                    found.add(comp.value)
                elif isinstance(op, (ast.In, ast.NotIn)) and isinstance(
                    comp, (ast.Tuple, ast.List)
                ):
                    found |= {e.value for e in comp.elts if isinstance(e, ast.Constant)}
                elif (
                    isinstance(op, (ast.Is, ast.IsNot))
                    and isinstance(comp, ast.Constant)
                    and comp.value is None
                ):
                    found.add(None)
        elif isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.Not):
            if is_target(node.operand):
                found.add(None)
        elif isinstance(node, ast.Match) and is_target(node.subject):
            for case in node.cases:
                pattern = case.pattern
                if isinstance(pattern, ast.MatchValue) and isinstance(
                    pattern.value, ast.Constant
                ):
                    found.add(pattern.value.value)
    return found


def _symbol_defined(path: Path, symbol: str) -> bool:
    tree = ast.parse(path.read_text())
    return any(
        isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
        and node.name == symbol
        for node in tree.body
    )


def verify(schema: dict) -> list[str]:
    """All parity and existence checks; returns one problem string each."""
    problems: list[str] = []
    choices_by_path = {f['path']: f['choices'] for f in schema['fields']}

    # Completeness: every module-selection field with at least one non-None
    # option must have a dispatch site here. accretion.module accepts only
    # None today, so it is exempt until an implementation lands.
    mapped = {site['config_path'] for site in DISPATCH_SITES}
    for field in schema['fields']:
        if not field['path'].endswith('.module') or field['path'].count('.') != 1:
            continue
        options = field['choices'] or []
        if any(o is not None for o in options) and field['path'] not in mapped:
            problems.append(
                f'{field["path"]} selects between {sorted(o for o in options if o)} '
                f'but has no DISPATCH_SITES entry'
            )

    for site in DISPATCH_SITES:
        cfg_path = site['config_path']
        options = choices_by_path.get(cfg_path)
        if options is None:
            problems.append(f'{cfg_path}: no in_() validator options found in the schema')
            continue
        declared = set(site['entries'])
        if declared != set(options):
            problems.append(
                f'{cfg_path}: declared entries {sorted(declared, key=str)} do not match '
                f'validator options {sorted(options, key=str)}'
            )
        wrapper = SRC / site['wrapper']
        compared = scan_compared_options(wrapper, tuple(cfg_path.split('.')))
        for option in options:
            if option is not None and option not in compared:
                problems.append(
                    f'{cfg_path}: option "{option}" is never dispatched in {site["wrapper"]}'
                )
        for entry_file, symbol, _role in site['entries'].values():
            if entry_file is None:
                continue
            impl = SRC / entry_file
            if not impl.is_file():
                problems.append(f'{cfg_path}: implementation file {entry_file} does not exist')
            elif not _symbol_defined(impl, symbol):
                problems.append(f'{cfg_path}: symbol "{symbol}" not found in {entry_file}')

    # Tree-wide validity: every module-name comparison anywhere in src must
    # use a real option; a typo in a guard would otherwise dead-arm silently.
    # KNOWN_DEAD_ARMS lists branches that compare against a non-option value
    # on purpose or pending a domain decision; each needs a reason.
    dotted_options = {
        tuple(site['config_path'].split('.')): set(
            choices_by_path.get(site['config_path']) or ()
        )
        for site in DISPATCH_SITES
    }
    for py in sorted(SRC.rglob('*.py')):
        for dotted, options in dotted_options.items():
            if not options:
                continue
            for value in scan_compared_options(py, dotted):
                rel = str(py.relative_to(REPO_ROOT))
                if (
                    value not in options
                    and (rel, '.'.join(dotted), value) not in KNOWN_DEAD_ARMS
                ):
                    problems.append(
                        f'{rel} compares {".".join(dotted)} '
                        f'against "{value}", which is not a validator option'
                    )

    for _area, _switch, entry_file, symbol, _doc in SUB_DISPATCHES:
        impl = SRC / entry_file
        if not impl.is_file() or not _symbol_defined(impl, symbol):
            problems.append(f'sub-dispatch symbol "{symbol}" not found in {entry_file}')
    return problems


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _fmt_option(option) -> str:
    return '`none`' if option is None else f'`"{option}"`'


def render() -> str:
    lines = [
        GENERATED_NOTE,
        "Module selection happens in each area's wrapper; invalid option values are",
        'rejected when the config file loads. Secondary switches within an area are',
        'listed below its table.',
    ]
    for site in DISPATCH_SITES:
        lines += ['', f'## {site["area"]} (`{site["config_path"]}`)', '']
        lines += ['| Option | Entry point | Role |', '|---|---|---|']
        for option in sorted(site['entries'], key=lambda o: (o is None, str(o))):
            entry_file, symbol, role = site['entries'][option]
            entry = f'`{entry_file}:{symbol}`' if entry_file else 'not applicable'
            lines.append(f'| {_fmt_option(option)} | {entry} | {role} |')
        subs = [s for s in SUB_DISPATCHES if s[0] == site['area']]
        if subs:
            lines.append('')
            for _area, switch, entry_file, symbol, doc in subs:
                lines.append(f'- {switch}: {doc} (`{entry_file}:{symbol}`).')
    return '\n'.join(lines)


def build_json() -> dict:
    sites = []
    for site in DISPATCH_SITES:
        sites.append(
            {
                'area': site['area'],
                'config_path': site['config_path'],
                'wrapper': f'src/proteus/{site["wrapper"]}',
                'options': [
                    {
                        'option': option,
                        'entry': f'src/proteus/{f}:{s}' if f else None,
                        'role': role,
                    }
                    for option, (f, s, role) in sorted(
                        site['entries'].items(), key=lambda kv: (kv[0] is None, str(kv[0]))
                    )
                ],
                'sub_dispatches': [
                    {'switch': sw, 'entry': f'src/proteus/{f}:{s}', 'doc': doc}
                    for area, sw, f, s, doc in SUB_DISPATCHES
                    if area == site['area']
                ],
            }
        )
    return {'sites': sites}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    _docgen.add_check_write_cli(parser)
    args = parser.parse_args()

    try:
        schema = _config_schema.build_schema()
        problems = verify(schema)
        content = PAGE.read_text() if PAGE.exists() else None
        if content is None:
            raise _docgen.DocgenError(f'{PAGE} does not exist')
        page = _docgen.normalize(
            _docgen.replace_between_markers(content, 'GENERATED: module-map', render())
        )
    except _config_schema.SchemaError as exc:
        print(f'[x] {exc}', file=sys.stderr)
        return 1
    except _docgen.DocgenError as exc:
        print(f'[x] {exc}', file=sys.stderr)
        return 2

    rc = 0
    for problem in problems:
        print(f'[x] {problem}')
        rc = 1

    targets = [(PAGE, page), (JSON_PATH, _docgen.dump_json(build_json()))]
    return max(rc, _docgen.run_generator(targets, check=args.check, regen_cmd=REGEN_CMD))


if __name__ == '__main__':
    sys.exit(main())
