#!/usr/bin/env python3
"""Regenerate the helpfile column reference from the source tree.

Renders one table per column group into the marker-delimited region of
``docs/Reference/output.md`` and writes the machine-readable sidecar
``docs/Reference/output_schema.json``. Columns, units, and descriptions come
from ``GetHelpfileKeys`` in ``src/proteus/utils/coupler.py``; the producer
and consumer attribution comes from a static scan of every source file (see
``_helpfile_scan``). Columns whose producer cannot be attributed statically
are listed in their own section rather than silently left blank.

Usage:
    python tools/generate_output_reference.py            # regenerate in place
    python tools/generate_output_reference.py --check    # verify, write nothing

Exit codes:
    0  committed output is current
    1  output is stale
    2  structural error (missing marker or page, unparseable source)
"""

from __future__ import annotations

import argparse
import sys

import _docgen
import _helpfile_scan
import _helpfile_schema

REPO_ROOT = _docgen.REPO_ROOT
PAGE = REPO_ROOT / 'docs' / 'Reference' / 'output.md'
JSON_PATH = REPO_ROOT / 'docs' / 'Reference' / 'output_schema.json'
REGEN_CMD = 'python tools/generate_output_reference.py'

GENERATED_NOTE = (
    '<!-- Generated by tools/generate_output_reference.py; '
    'edit src/proteus/, not these tables -->'
)

HEADER_NOTE = (
    'Each iteration carries the previous row forward and overwrites only the '
    'columns the active modules produce, so a column whose producer is not '
    'part of the current configuration keeps its previous value (initially '
    'zero) for the whole run. The "written when" column names the '
    'configuration that actually writes each column. The "Read by" column '
    'names modules that consume each column, and can over-approximate when '
    'consumers read keys through variable or template loops, or under-approximate '
    'when consumers read keys dynamically at runtime through computed keys. '
    'The "(possible)" label marks consumers in consumers_possible that read '
    'columns only conditionally, such as for specific species.'
)

TOUCHED_PATTERNS: dict[tuple[str, str], str] = {
    ('src/proteus/atmos_clim/agni.py', '_validate_surface_state'): 'T_surf, T_magma, P_surf',
    ('src/proteus/escape/boreas.py', '_set_boreas_params'): '<gas>_vmr_xuv',
    (
        'src/proteus/escape/common.py',
        'calc_unfract_fluxes',
    ): '<element>_kg_total, <element>_kg_atm',
    ('src/proteus/escape/wrapper.py', 'escapable_mass'): '<element>_kg_total, <element>_kg_atm',
    (
        'src/proteus/escape/wrapper.py',
        'calc_new_elements',
    ): '<element>_kg_total, <element>_kg_atm',
    ('src/proteus/observe/petitRADTRANS.py', '_get_mix'): '<gas>_vmr',
    ('src/proteus/outgas/atmodeller.py', '_populate_volatile_element_reservoirs'): (
        '<species>_kg_<reservoir>'
    ),
    ('src/proteus/outgas/atmodeller.py', 'calc_surface_pressures_atmodeller'): (
        '<element>_kg_total'
    ),
    ('src/proteus/plot/cpl_global.py', 'plot_global'): 'F_int, F_atm, F_olr, F_tidal, F_radio',
    ('src/proteus/plot/cpl_orbit.py', '_plot_orbit_snapshot'): (
        'semimajorax, semimajorax_sat, eccentricity, eccentricity_sat'
    ),
}

# Conditions for backend files reached through a dispatch layer that the
# module map's entry table does not name directly.
FILE_CONDITIONS = {
    'interior_energetics/aragog_jax.py': 'interior_energetics.module = "aragog"',
    'interior_struct/zalmoxis.py': 'interior_struct.module = "zalmoxis"',
    'interior_struct/dummy.py': 'interior_struct.module = "dummy"',
    'outgas/lavatmos.py': 'outgas.vapourise = true',
    'outgas/binodal.py': 'h2 binodal enabled',
    'orbit/orbit.py': 'orbit.evolve = true',
    'orbit/satellite.py': 'orbit.satellite = true',
    'escape/common.py': 'escape enabled',
}

# Wrapper functions that run only under one module option; writes elsewhere
# in shared wrapper files are unconditional at this granularity.
FUNCTION_CONDITIONS = {
    ('escape/wrapper.py', 'run_zephyrus'): 'escape.module = "zephyrus"',
    ('escape/wrapper.py', 'run_dummy'): 'escape.module = "dummy"',
    ('interior_energetics/wrapper.py', '_remelt_aragog'): (
        'giant impact, interior_energetics.module = "aragog"'
    ),
    (
        'interior_struct/common.py',
        'record_volatile_change',
    ): 'interior_struct.module = "zalmoxis"',
    (
        'interior_energetics/aragog.py',
        '_write_core_module_diagnostics',
    ): 'interior_energetics.aragog.core_bc = "core_module"',
}


def _condition_maps() -> dict[str, str]:
    """File-level conditions derived from the module map declarations."""
    import generate_module_map as gmm

    conditions = dict(FILE_CONDITIONS)
    for site in gmm.DISPATCH_SITES:
        for option, (entry_file, _symbol, _role) in site['entries'].items():
            if entry_file is None or entry_file.endswith('wrapper.py'):
                continue
            conditions.setdefault(entry_file, f'{site["config_path"]} = "{option}"')
    return conditions


def _consumer_module(rel_file: str) -> str:
    if '/' not in rel_file:
        return 'main loop'
    return rel_file.split('/')[0]


def build_matrix() -> dict:
    """Join the parsed schema with the producer/consumer scan."""
    schema = _helpfile_schema.parse_schema()
    scan = _helpfile_scan.scan_tree()
    file_conditions = _condition_maps()

    # Producers are deduplicated to (file, condition); the writing function
    # is dropped from the record to keep the committed JSON compact.
    producers: dict[str, list[dict]] = {}
    for rel_file, function, key in scan['writes']:
        condition = FUNCTION_CONDITIONS.get(
            (rel_file, function), file_conditions.get(rel_file, 'always')
        )
        entry = {'file': f'src/proteus/{rel_file}', 'condition': condition}
        bucket = producers.setdefault(key, [])
        if entry not in bucket:
            bucket.append(entry)

    consumers_definite: dict[str, set[str]] = {}
    consumers_possible: dict[str, set[str]] = {}
    for rel_file, key, is_possible in scan['reads']:
        bucket = consumers_possible if is_possible else consumers_definite
        bucket.setdefault(key, set()).add(_consumer_module(rel_file))

    for key, poss in consumers_possible.items():
        poss -= consumers_definite.get(key, set())

    keys = []
    for record in schema:
        name = record['name']
        definite = consumers_definite.get(name, set())
        possible = consumers_possible.get(name, set())
        keys.append(
            {
                **record,
                'producers': sorted(
                    producers.get(name, []), key=lambda p: (p['file'], p['condition'])
                ),
                'consumers': sorted(definite | possible),
                'consumers_possible': sorted(possible),
            }
        )
    return {
        'note': (
            'The consumers field names modules that consume each column, '
            'and can over-approximate when consumers read keys through '
            'variable or template loops, or under-approximate when consumers '
            'read keys dynamically at runtime through computed keys. '
            'The consumers_possible field lists the subset of consumers that '
            'read columns only conditionally, such as for specific species.'
        ),
        'keys': keys,
        'unresolved_events': [
            {
                'file': f'src/proteus/{f}',
                'kind': kind,
                'reason': reason,
                'function': func,
            }
            for f, _line, reason, kind, func in scan['unresolved']
        ],
    }


def _producer_cells(producers: list[dict]) -> tuple[str, str]:
    """(producer, written-when) cells, deduplicated file-first."""
    if not producers:
        return 'not statically attributed', 'see below'
    files = []
    conditions = []
    for p in producers:
        short = p['file'].removeprefix('src/proteus/')
        if short not in files:
            files.append(short)
        if p['condition'] not in conditions:
            conditions.append(p['condition'])
    if 'always' in conditions and len(conditions) > 1:
        conditions.remove('always')
        conditions.insert(0, 'always')
    return '<br>'.join(f'`{f}`' for f in files), '; '.join(conditions)


def _consumer_cells(key: dict) -> str:
    """Format consumers with (possible) annotations where applicable."""
    possible = set(key['consumers_possible'])
    mods = [f'{mod} (possible)' if mod in possible else mod for mod in key['consumers']]
    return ', '.join(mods) if mods else ' '


def render(matrix: dict) -> str:
    lines = [GENERATED_NOTE, HEADER_NOTE]
    groups: dict[str, list[dict]] = {}
    for key in matrix['keys']:
        groups.setdefault(key['group'], []).append(key)
    for group, keys in groups.items():
        lines += ['', f'### {group}', '']
        lines += [
            '| Column | Unit | Description | Producer | Written when | Read by |',
            '|---|---|---|---|---|---|',
        ]
        for key in keys:
            producer, condition = _producer_cells(key['producers'])
            unit = f'`{key["unit"]}`' if key['unit'] else ' '
            readers = _consumer_cells(key)
            description = key['description'].replace('|', '\\|')
            lines.append(
                f'| `{key["name"]}` | {unit} | {description} | {producer} '
                f'| {condition} | {readers} |'
            )
    unresolved = [k for k in matrix['keys'] if not k['producers']]
    if unresolved:
        lines += ['', '### Columns without a statically attributed producer', '']
        for key in unresolved:
            lines.append(f'- `{key["name"]}` ({key["unit"] or "no unit"})')

    for kind, action in (('read', 'accessed'), ('write', 'modified')):
        events = [e for e in matrix.get('unresolved_events', []) if e['kind'] == kind]
        if not events:
            continue
        lines += ['', f'### {kind.capitalize()}s with computed keys', '']
        lines.append(
            f'A computed key is a helpfile column name constructed dynamically at '
            f'runtime through variable lookups or formatted strings. Because static '
            f'analysis cannot determine the {action} column names in advance, these '
            f'{kind} sites are not attributed to specific columns in the table above.'
        )
        lines.append('')
        counts: dict[tuple[str, str, str], int] = {}
        for event in events:
            evt_key = (event['file'], event['function'], event['reason'])
            counts[evt_key] = counts.get(evt_key, 0) + 1
        for (file, func, reason), count in counts.items():
            pattern = TOUCHED_PATTERNS.get((file, func))
            pattern_str = f' (touches {pattern})' if pattern else ''
            sites_str = f' ({count} sites)' if count > 1 else ''
            lines.append(f'- `{file}::{func}`{sites_str}: `{reason}`{pattern_str}')

    return '\n'.join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    _docgen.add_check_write_cli(parser)
    args = parser.parse_args()

    try:
        matrix = build_matrix()
        if not PAGE.exists():
            raise _docgen.DocgenError(f'{PAGE} does not exist')
        page = _docgen.normalize(
            _docgen.replace_between_markers(
                PAGE.read_text(), 'GENERATED: helpfile-matrix', render(matrix)
            )
        )
    except _docgen.DocgenError as exc:
        print(f'[x] {exc}', file=sys.stderr)
        return 2

    targets = [(PAGE, page), (JSON_PATH, _docgen.dump_json(matrix))]
    return _docgen.run_generator(targets, check=args.check, regen_cmd=REGEN_CMD)


if __name__ == '__main__':
    sys.exit(main())
