#!/usr/bin/env python3
"""Regenerate the configuration reference tables from the config schema.

Renders one parameter table per TOML section into marker-delimited regions of
the seven pages under ``docs/Reference/config/``, writes the machine-readable
sidecar ``docs/Reference/config/config_schema.json``, and verifies that
``input/all_options.toml`` and the schema agree key-for-key in both
directions. Table content (types, defaults, choices, bounds, descriptions)
comes from the attrs classes under ``src/proteus/config/``; edit those, not
the tables.

Usage:
    python tools/generate_config_reference.py            # regenerate in place
    python tools/generate_config_reference.py --check    # verify, write nothing

Exit codes:
    0  committed output is current and all_options.toml matches the schema
    1  output is stale, or all_options.toml diverges from the schema
    2  structural error (missing marker, unrecognised schema internals)
"""

from __future__ import annotations

import argparse
import re
import sys
import tomllib

import _config_schema
import _docgen
from _docgen import REPO_ROOT

CONFIG_DOCS = REPO_ROOT / 'docs' / 'Reference' / 'config'
ALL_OPTIONS = REPO_ROOT / 'input' / 'all_options.toml'
JSON_PATH = CONFIG_DOCS / 'config_schema.json'
REGEN_CMD = 'python tools/generate_config_reference.py'

# Page that renders each top-level TOML section ('' is the root, holding
# config_version). Every section produced by the schema walk must resolve
# through this map; an unmapped top-level section is a structural error.
PAGE_MAP = {
    '': 'params.md',
    'params': 'params.md',
    'planet': 'planet.md',
    'star': 'star_orbit.md',
    'orbit': 'star_orbit.md',
    'interior_struct': 'interior.md',
    'interior_energetics': 'interior.md',
    'atmos_clim': 'atmosphere.md',
    'atmos_chem': 'atmosphere.md',
    'escape': 'escape_outgas.md',
    'outgas': 'escape_outgas.md',
    'observe': 'observe.md',
    'accretion': 'observe.md',
}

# Dotted paths deliberately absent from input/all_options.toml, each with a
# reason. Keys listed here are excluded from the two-way completeness check.
ALL_OPTIONS_EXCEPTIONS: dict[str, str] = {}

GENERATED_NOTE = (
    '<!-- Generated by tools/generate_config_reference.py; '
    'edit src/proteus/config/, not this table -->'
)


def _fmt_choice(value) -> str:
    if value is None:
        return '`none`'
    if isinstance(value, str):
        return f'`"{value}"`'
    return f'`{value}`'


def _describe(field: dict) -> str:
    """Description cell: prose plus rendered choices and bounds."""
    parts = []
    if field['description']:
        prose = field['description']
        if field['choices']:
            # The validator's option list is authoritative; drop a trailing
            # hand-written "Choices: ..." sentence so it is not repeated.
            prose = re.sub(r'\s*Choices:[^.]*\.?\s*$', '', prose)
        if prose:
            parts.append(prose.rstrip('.') + '.')
    if field['choices']:
        parts.append('Choices: ' + ', '.join(_fmt_choice(c) for c in field['choices']) + '.')
    if field['bounds']:
        clauses = ' and '.join(f'{b["op"]} {b["value"]}' for b in field['bounds'])
        parts.append(f'Must be {clauses}.')
    return ' '.join(parts).replace('|', '\\|')


def _section_table(fields: list[dict]) -> str:
    rows = ['| Parameter | Type | Default | Description |', '|---|---|---|---|']
    for f in fields:
        name = f['path'].rsplit('.', 1)[-1]
        default = f['default'] if f['default'] == 'required' else f'`{f["default"]}`'
        rows.append(f'| `{name}` | {f["type"]} | {default} | {_describe(f)} |')
    return GENERATED_NOTE + '\n' + '\n'.join(rows)


def _constraints_block(constraints: list[dict]) -> str:
    lines = [GENERATED_NOTE, 'Cross-field constraints enforced when the config file loads:', '']
    for c in sorted(constraints, key=lambda c: c['validator']):
        lines.append(f'- {c["doc"].rstrip(".")}.')
    return '\n'.join(lines)


def _page_for(path_or_section: str) -> str:
    """Page filename for a dotted path; root-level fields fall back to the root page."""
    return PAGE_MAP.get(path_or_section.split('.')[0], PAGE_MAP[''])


def build_targets(schema: dict) -> list:
    """Render every page and the JSON sidecar as (path, content) targets."""
    sections: dict[str, list[dict]] = {}
    for f in schema['fields']:
        sections.setdefault(f['toml_section'], []).append(f)

    page_sections: dict[str, list[str]] = {}
    for section in sections:
        top = section.split('.')[0]
        if top not in PAGE_MAP:
            raise _docgen.DocgenError(f'section "[{section}]" has no PAGE_MAP entry')
        page_sections.setdefault(PAGE_MAP[top], []).append(section)

    page_constraints: dict[str, list[dict]] = {page: [] for page in set(PAGE_MAP.values())}
    for c in schema['constraints']:
        page_constraints[_page_for(c['attached_to'][0])].append(c)

    targets = []
    for page in sorted(page_sections):
        path = CONFIG_DOCS / page
        if not path.exists():
            raise _docgen.DocgenError(f'config page {path} does not exist')
        content = path.read_text()
        for section in page_sections[page]:
            marker = f'GENERATED: config-table [{section or "root"}]'
            content = _docgen.replace_between_markers(
                content, marker, _section_table(sections[section])
            )
        content = _docgen.replace_between_markers(
            content,
            f'GENERATED: config-constraints {page.removesuffix(".md")}',
            _constraints_block(page_constraints[page]),
        )
        targets.append((path, _docgen.normalize(content)))

    targets.append((JSON_PATH, _docgen.dump_json(schema)))
    return targets


def check_all_options(schema: dict) -> list[str]:
    """Two-way key comparison between the schema and input/all_options.toml."""

    def flatten(data: dict, prefix: str = '') -> set[str]:
        out: set[str] = set()
        for key, value in data.items():
            path = f'{prefix}.{key}' if prefix else key
            if isinstance(value, dict):
                out |= flatten(value, path)
            else:
                out.add(path)
        return out

    with open(ALL_OPTIONS, 'rb') as fh:
        file_keys = flatten(tomllib.load(fh))
    schema_keys = {f['path'] for f in schema['fields']}
    excused = set(ALL_OPTIONS_EXCEPTIONS)

    problems = []
    for key in sorted(file_keys - schema_keys - excused):
        problems.append(f'all_options.toml key "{key}" does not exist in the config schema')
    for key in sorted(schema_keys - file_keys - excused):
        problems.append(f'schema field "{key}" is missing from input/all_options.toml')
    for key in sorted(excused - schema_keys - file_keys):
        problems.append(f'ALL_OPTIONS_EXCEPTIONS entry "{key}" matches nothing; remove it')
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    _docgen.add_check_write_cli(parser)
    args = parser.parse_args()

    try:
        schema = _config_schema.build_schema()
        targets = build_targets(schema)
    except _config_schema.SchemaError as exc:
        print(f'[x] {exc}', file=sys.stderr)
        return 1
    except _docgen.DocgenError as exc:
        print(f'[x] {exc}', file=sys.stderr)
        return 2

    rc = 0
    for problem in check_all_options(schema):
        print(f'[x] {problem}')
        rc = 1

    undocumented = sum(1 for f in schema['fields'] if f['doc_source'] == 'missing')
    if undocumented:
        print(f'[!] {undocumented} fields have no description in any source channel')

    rc = max(rc, _docgen.run_generator(targets, check=args.check, regen_cmd=REGEN_CMD))
    return rc


if __name__ == '__main__':
    sys.exit(main())
