#!/usr/bin/env python3
"""Regenerate the helpfile column reference from the source tree.

Renders one table per column group into the marker-delimited region of
``docs/Reference/output.md`` and writes the machine-readable sidecar
``docs/Reference/output_schema.json``. Columns, units, and descriptions come
from ``GetHelpfileKeys`` in ``src/proteus/utils/coupler.py``; the producer
and consumer attribution comes from a static scan of every source file (see
``_helpfile_scan``). Columns whose producer cannot be attributed statically
are listed in their own section rather than silently left blank.

Usage:
    python tools/generate_output_reference.py            # regenerate in place
    python tools/generate_output_reference.py --check    # verify, write nothing

Exit codes:
    0  committed output is current
    1  output is stale
    2  structural error (missing marker or page, unparseable source)
"""

from __future__ import annotations

import argparse
import sys

import _docgen
import _helpfile_scan
import _helpfile_schema
from _docgen import REPO_ROOT

PAGE = REPO_ROOT / 'docs' / 'Reference' / 'output.md'
JSON_PATH = REPO_ROOT / 'docs' / 'Reference' / 'output_schema.json'
REGEN_CMD = 'python tools/generate_output_reference.py'

GENERATED_NOTE = (
    '<!-- Generated by tools/generate_output_reference.py; '
    'edit src/proteus/, not these tables -->'
)

HEADER_NOTE = (
    'Each iteration carries the previous row forward and overwrites only the '
    'columns the active modules produce, so a column whose producer is not '
    'part of the current configuration keeps its previous value (initially '
    'zero) for the whole run. The "written when" column names the '
    'configuration that actually writes each column.'
)

# Conditions for backend files reached through a dispatch layer that the
# module map's entry table does not name directly.
FILE_CONDITIONS = {
    'interior_energetics/aragog_jax.py': 'interior_energetics.module = "aragog"',
    'interior_struct/zalmoxis.py': 'interior_struct.module = "zalmoxis"',
    'interior_struct/dummy.py': 'interior_struct.module = "dummy"',
    'outgas/lavatmos.py': 'outgas.vapourise = true',
    'outgas/binodal.py': 'h2 binodal enabled',
    'orbit/orbit.py': 'orbit.evolve = true',
    'orbit/satellite.py': 'orbit.satellite = true',
    'escape/common.py': 'escape enabled',
}

# Wrapper functions that run only under one module option; writes elsewhere
# in shared wrapper files are unconditional at this granularity.
FUNCTION_CONDITIONS = {
    ('escape/wrapper.py', 'run_zephyrus'): 'escape.module = "zephyrus"',
    ('escape/wrapper.py', 'run_dummy'): 'escape.module = "dummy"',
}


def _condition_maps() -> dict[str, str]:
    """File-level conditions derived from the module map declarations."""
    import generate_module_map as gmm

    conditions = dict(FILE_CONDITIONS)
    for site in gmm.DISPATCH_SITES:
        for option, (entry_file, _symbol, _role) in site['entries'].items():
            if entry_file is None or entry_file.endswith('wrapper.py'):
                continue
            conditions.setdefault(entry_file, f'{site["config_path"]} = "{option}"')
    return conditions


def _consumer_module(rel_file: str) -> str:
    if '/' not in rel_file:
        return 'main loop'
    return rel_file.split('/')[0]


def build_matrix() -> dict:
    """Join the parsed schema with the producer/consumer scan."""
    schema = _helpfile_schema.parse_schema()
    scan = _helpfile_scan.scan_tree()
    file_conditions = _condition_maps()

    # Producers are deduplicated to (file, condition); the writing function
    # is dropped from the record to keep the committed JSON compact.
    producers: dict[str, list[dict]] = {}
    for rel_file, function, key in scan['writes']:
        condition = FUNCTION_CONDITIONS.get(
            (rel_file, function), file_conditions.get(rel_file, 'always')
        )
        entry = {'file': f'src/proteus/{rel_file}', 'condition': condition}
        bucket = producers.setdefault(key, [])
        if entry not in bucket:
            bucket.append(entry)

    consumers: dict[str, set[str]] = {}
    for rel_file, key in scan['reads']:
        consumers.setdefault(key, set()).add(_consumer_module(rel_file))

    keys = []
    for record in schema:
        name = record['name']
        keys.append(
            {
                **record,
                'producers': sorted(
                    producers.get(name, []), key=lambda p: (p['file'], p['condition'])
                ),
                'consumers': sorted(consumers.get(name, set())),
            }
        )
    return {
        'keys': keys,
        'unresolved_events': [
            {'file': f'src/proteus/{f}', 'line': line, 'reason': reason}
            for f, line, reason in scan['unresolved']
        ],
    }


def _producer_cells(producers: list[dict]) -> tuple[str, str]:
    """(producer, written-when) cells, deduplicated file-first."""
    if not producers:
        return 'not statically attributed', 'see below'
    files = []
    conditions = []
    for p in producers:
        short = p['file'].removeprefix('src/proteus/')
        if short not in files:
            files.append(short)
        if p['condition'] not in conditions:
            conditions.append(p['condition'])
    if 'always' in conditions and len(conditions) > 1:
        conditions.remove('always')
        conditions.insert(0, 'always')
    return '<br>'.join(f'`{f}`' for f in files), '; '.join(conditions)


def render(matrix: dict) -> str:
    lines = [GENERATED_NOTE, HEADER_NOTE]
    groups: dict[str, list[dict]] = {}
    for key in matrix['keys']:
        groups.setdefault(key['group'], []).append(key)
    for group, keys in groups.items():
        lines += ['', f'### {group}', '']
        lines += [
            '| Column | Unit | Description | Producer | Written when | Read by |',
            '|---|---|---|---|---|---|',
        ]
        for key in keys:
            producer, condition = _producer_cells(key['producers'])
            unit = f'`{key["unit"]}`' if key['unit'] else ' '
            readers = ', '.join(key['consumers']) if key['consumers'] else ' '
            description = key['description'].replace('|', '\\|')
            lines.append(
                f'| `{key["name"]}` | {unit} | {description} | {producer} '
                f'| {condition} | {readers} |'
            )
    unresolved = [k for k in matrix['keys'] if not k['producers']]
    lines += ['', '### Columns without a statically attributed producer', '']
    if unresolved:
        for key in unresolved:
            lines.append(f'- `{key["name"]}` ({key["unit"] or "no unit"})')
        lines.append('')
        lines.append('Unattributed write sites:')
        for event in matrix['unresolved_events']:
            lines.append(f'- `{event["file"]}:{event["line"]}`: {event["reason"]}')
    else:
        lines.append(
            'None; every column above has at least one statically attributed producer.'
        )
    return '\n'.join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    _docgen.add_check_write_cli(parser)
    args = parser.parse_args()

    try:
        matrix = build_matrix()
        if not PAGE.exists():
            raise _docgen.DocgenError(f'{PAGE} does not exist')
        page = _docgen.normalize(
            _docgen.replace_between_markers(
                PAGE.read_text(), 'GENERATED: helpfile-matrix', render(matrix)
            )
        )
    except _docgen.DocgenError as exc:
        print(f'[x] {exc}', file=sys.stderr)
        return 2

    targets = [(PAGE, page), (JSON_PATH, _docgen.dump_json(matrix))]
    return _docgen.run_generator(targets, check=args.check, regen_cmd=REGEN_CMD)


if __name__ == '__main__':
    sys.exit(main())
