#!/bin/bash
# Download and compile socrates
#
# Usage:
#   tools/get_socrates.sh            # install into ./socrates/
#   tools/get_socrates.sh some/path  # custom destination, created if missing
#   tools/get_socrates.sh --force    # discard an existing checkout

# Do we have NetCDF?
if ! [ -x "$(command -v nc-config)" ]; then
  echo 'ERROR: NetCDF is not installed.' >&2
  exit 1
fi
if ! [ -x "$(command -v nf-config)" ]; then
  echo 'ERROR: NetCDF-Fortran library is not installed.' >&2
  exit 1
fi

# Do we have gfortran?
if ! [ -x "$(command -v gfortran)" ]; then
  echo 'ERROR: gfortran compiler is not installed.' >&2
  exit 1
fi

# Already setup?
if [ -n "$RAD_DIR" ]; then
    echo "WARNING: You already have SOCRATES installed"
    echo "         RAD_DIR=$RAD_DIR"
    echo "Reinstalling SOCRATES..."
    echo ""
    sleep 5
fi

# Shared helpers: see tools/_get_common.sh.
_get_common="$(dirname "${BASH_SOURCE[0]}")/_get_common.sh"
if [ ! -f "$_get_common" ]; then
    echo "ERROR: $_get_common is missing; use a complete PROTEUS checkout." >&2
    exit 1
fi
source "$_get_common"

# Check SSH access to GitHub.
use_ssh=$(github_use_ssh)

# Disable SSH (uncomment to allow SSH clone of SOCRATES)
# use_ssh=false

# Download
root="$proteus_root"

# Separate the --force flag from the optional install-path argument.
get_parse_args "$@"

if [ -n "$get_install_path" ]; then
    socpath="$(portable_realpath "$get_install_path")"
    # set -euo pipefail is not active yet, so an unresolvable path would
    # otherwise reach git clone as an empty string.
    if [ -z "$socpath" ]; then
        echo "ERROR: could not resolve install path '$get_install_path'." >&2
        exit 1
    fi
else
    socpath="$root/socrates"
fi

# make/Mk_cmd is excluded from the dirty test: configure regenerates it on
# every build (compiler detection, host paths, and optimisation flags), so
# it is regenerable build config rather than user work and would otherwise
# block every refresh.
guard_dirty_checkout "$socpath" get_socrates.sh -- ':(exclude)make/Mk_cmd'
rm -rf "$socpath"

set -euo pipefail


# Resolve the pinned URL + ref from pyproject.toml. The HTTPS URL is the
# default; SSH is used only when ssh -T against github succeeded above.
resolve_module_pin socrates
soc_url="$module_url"
soc_ref="$module_ref"

if [ "$use_ssh" = true ]; then
    git clone "$(github_ssh_url "$soc_url")" "$socpath"
else
    git clone "$soc_url" "$socpath"
fi

# Pin to the configured SHA / tag / branch.
git -C "$socpath" checkout --quiet "$soc_ref"

# Compile SOCRATES
cd "$socpath"
./configure

# A missing make/Mk_cmd means the configure step did not produce its
# output (or the file moved); report that directly instead of failing
# later in a less obvious place.
if [ ! -f make/Mk_cmd ]; then
    echo "ERROR: make/Mk_cmd was not generated by the SOCRATES configure" >&2
    echo "       step. Check the configure output above for the failure." >&2
    exit 1
fi

# Compile against a portable instruction set when SOCRATES_PORTABLE_FLAGS=1.
# The SOCRATES configure script sets the optimisation flags to "-Ofast
# -march=native", which bakes the build host's specific CPU extensions
# into the binaries; such a binary aborts with an illegal-instruction
# fault if the compiled tree is reused on a host whose CPU lacks those
# extensions. CI sets this switch because its compiled trees are cached
# and restored across runner machines with mixed CPU generations. Local
# builds keep the upstream flags for performance by default; set the
# switch for bit-reproducible science runs or when an install is copied
# between machines (e.g. heterogeneous cluster nodes). The portable
# spelling is "-O2 -fno-fast-math", which runs on any CPU and avoids
# fast-math value reordering.
#
# The rewrite requires the exact flag string configure writes today, so
# a SOCRATES release that changes the optimisation flags stops the build
# here, where the fix is a one-line update, rather than compiling a
# host-specific binary that fails far away from its cause.

# CPU-specific flag spellings across the compilers the committed Mk_cmd
# templates use (gfortran -march/-mcpu, ifort/ifx -xHost/-ax<arch>).
nonportable_flags='-march=|-mcpu=native|-Ofast|-xHost|-ax[A-Z]'

if [ "${SOCRATES_PORTABLE_FLAGS:-0}" = "1" ]; then
    if ! grep -q -- '-Ofast -march=native' make/Mk_cmd; then
        echo "ERROR: the SOCRATES configure script did not write the expected" >&2
        echo "       '-Ofast -march=native' optimisation flags; its defaults have" >&2
        echo "       changed. Update the flag rewrite in tools/get_socrates.sh." >&2
        exit 1
    fi
    sed 's/-Ofast -march=native/-O2 -fno-fast-math/g' make/Mk_cmd > make/Mk_cmd.portable
    mv make/Mk_cmd.portable make/Mk_cmd

    # Belt-and-braces net behind the exact-string check above.
    if grep -qE -- "$nonportable_flags" make/Mk_cmd; then
        echo "ERROR: non-portable optimisation flags remain in make/Mk_cmd." >&2
        echo "       Update the flag rewrite in tools/get_socrates.sh to match" >&2
        echo "       the current SOCRATES configure output." >&2
        grep -nE -- "$nonportable_flags" make/Mk_cmd >&2
        exit 1
    fi
fi

./build_code

# Verify the flags that reached the compiler (portable mode only).
# build_code copies make/Mk_cmd into bin/Mk_cmd before compiling, but on
# recognised cluster hostnames it replaces bin/Mk_cmd with a committed
# per-host template (bin/Mk_cmd_<host>), which may carry host-specific
# optimisation flags. Check the file make actually read, so a template
# carrying any of the known CPU-specific flags cannot silently produce
# a non-portable binary.
if [ "${SOCRATES_PORTABLE_FLAGS:-0}" = "1" ] && grep -qE -- "$nonportable_flags" bin/Mk_cmd; then
    echo "ERROR: SOCRATES was compiled with non-portable optimisation flags." >&2
    echo "       A per-host Mk_cmd template likely replaced the portable" >&2
    echo "       flags during build_code; edit or remove the template and" >&2
    echo "       rebuild." >&2
    grep -nE -- "$nonportable_flags" bin/Mk_cmd >&2
    exit 1
fi

# Environment
export RAD_DIR=$socpath
cd $root

# Check radlib exists
radlib="$socpath/bin/radlib.a"
if [ -f "$radlib" ]; then
    echo "SOCRATES has been installed"
    echo ""
else
    echo "Could not find compiled SOCRATES binaries - failed to compile"
    exit 1
fi


# Inform user
echo "You must now run the following command:"
echo "    export RAD_DIR='$socpath'"
echo " "
echo "You should also add this command to your shell rc file (e.g. ~/.bashrc)"

# Re-cloning the SOCRATES tree deleted the build products AGNI writes into it:
# the generated wrappers under socrates/julia/gen and the compiled libSOCRATES
# under socrates/julia/lib. AGNI fails to precompile until they are rebuilt.
# proteus install-all and proteus update-all rebuild AGNI in a later step, so
# this note is for users who ran the script on its own.
if [ -d "$root/AGNI" ]; then
    echo " "
    echo "NOTE: this rebuild removed AGNI's compiled SOCRATES wrappers under"
    echo "      socrates/julia. If you ran this script directly (not via"
    echo "      proteus install-all / update-all, which rebuild AGNI for you),"
    echo "      regenerate them before running PROTEUS:"
    echo "          RAD_DIR=\"$socpath\" bash \"$root/tools/get_agni.sh\" 0"
fi
exit 0
