star_model = 0
star_mass = 1
star_radius_modern = 1
star_temperature_modern = 5772.0
star_luminosity_modern = 1
star_age_modern = 4567000000.0
star_rot_pctle = 50.0
star_spectrum = "stellar_spectra/Named/sun.txt"
semimajoraxis = 1
mass = 1
radius = 1
zenith_angle = 48.19
asf_scalefactor = 0.375
albedo_s = 0.1
albedo_pl = 0.1
eccentricity = 0.0
P_top = 1e-6
iter_max = 9000
log_level = "DEBUG"
dir_output = "dummy"
time_star = 100000000.0
time_target = 4567000000.0
spectral_file = "spectral_files/Frostflow/48/Frostflow.sf"
stellar_heating = 1
plot_iterfreq = 50
plot_format = "png"
sspec_dt_update = 1000000000.0
sinst_dt_update = 10.0
dt_maximum = 30000000.0
dt_minimum = 100.0
dt_method = 1
dt_propconst = 52.0
dt_atol = 0.02
dt_rtol = 0.05
dt_initial = 100.0
shallow_ocean_layer = 0
F_atm_bc = 0
skin_d = 0.01
skin_k = 2.0
prevent_warming = 0
solid_stop = 0
phi_crit = 0.005
steady_stop = 0
steady_flux = 0.8
steady_dprel = 1e-9
emit_stop = 0
F_crit = 0.2
escape_model = 2
escape_stop = 0.0003
escape_dummy_rate = 1000000.0
atmosphere_model = 2
atmosphere_surf_state = 1
atmosphere_nlev = 40
min_temperature = 0.5
max_temperature = 5000.0
water_cloud = 0
alpha_cloud = 0.0
tropopause = 0
rayleigh = 1
atmosphere_chemistry = 0
interior_model = 2
interior_nlev = 220
grain_size = 0.1
mixing_length = 2
solver_tolerance = 1e-10
tsurf_poststep_change = 30.0
tsurf_poststep_change_frac = 0.02
planet_coresize = 0.55
ic_adiabat_entropy = 2700.0
ic_dsdr = -4.698e-6
F_atm = 1000000.0
fO2_shift_IW = 2
solvevol_use_params = 1
Phi_global = 1.0
CH_ratio = 1.0
hydrogen_earth_oceans = 6.0
nitrogen_ppmw = 2.0
sulfur_ppmw = 200.0
H2O_included = 1
H2O_initial_bar = 0.0
CO2_included = 1
CO2_initial_bar = 0.0
N2_included = 1
N2_initial_bar = 0.0
S2_included = 1
S2_initial_bar = 0.0
SO2_included = 1
SO2_initial_bar = 0.0
H2_included = 1
H2_initial_bar = 0.0
CH4_included = 1
CH4_initial_bar = 0.0
CO_included = 1
CO_initial_bar = 0.0
