name: Tests for PROTEUS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  test:
    if: github.event.pull_request.draft == false
    name: Run Coverage and Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    env:
      FWL_DATA: /home/runner/work/fwl_data
      RAD_DIR: ./SOCRATES
      SOCRATES: ./SOCRATES  # https://github.com/FormingWorlds/JANUS/issues/51

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'false'

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v3
        id: cache-virtualenv
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}

      - name: Install dependencies
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
        run: |
          python -m pip install -e .[develop]

      - name: Install JANUS+MORS
        run: |
          python -m pip install git+https://github.com/FormingWorlds/MORS
          python -m pip install git+https://github.com/FormingWorlds/JANUS

      - name: Setup system for SOCRATES
        run: |
          sudo apt-get update
          sudo apt-get install libnetcdff-dev netcdf-bin

      - name: Get SOCRATES
        uses: actions/checkout@v4
        with:
          repository: 'FormingWorlds/SOCRATES'
          path: 'SOCRATES'

      - uses: actions/cache@v3
        id: cache-socrates
        with:
          path: |
            SOCRATES/bin
            SOCRATES/sbin
            SOCRATES/set_rad_env
          key: socrates-${{ hashFiles('SOCRATES/version') }}

      - name: Build SOCRATES
        if: steps.cache-socrates.outputs.cache-hit != 'true'
        run: |
          export LD_LIBRARY_PATH=""
          cd SOCRATES
          ./configure
          ./build_code
          cd ..

      - uses: actions/cache@v3
        id: cache-fwl-data
        with:
          path: ${{ env.FWL_DATA }}
          key: fwl-data-2

      - name: Pre-download fwl data
        if: steps.cache-fwl-data.cache-hit != 'true'
        run: |
          mors download all
          janus download stellar
          janus download spectral
          janus download spectral -n Frostflow -b 48

      - name: Test with pytest
        run: |
          source PROTEUS.env
          coverage run -m pytest

      - name: Report coverage
        run: |
          coverage json
          export TOTAL=$(python -c "import json;print(json.load(open('coverage.json'))['totals']['percent_covered_display'])")
          echo "total=$TOTAL" >> $GITHUB_ENV
          echo "### Total coverage: ${TOTAL}%" >> $GITHUB_STEP_SUMMARY
          echo $'\n```' >> $GITHUB_STEP_SUMMARY
          coverage report >> $GITHUB_STEP_SUMMARY
          echo $'\n```' >> $GITHUB_STEP_SUMMARY

      - name: Make coverage badge
        if: ${{ github.ref == 'refs/heads/master' && matrix.python-version == '3.10' }}
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: b4ee7dab92e20644bcb3a5ad09f71165
          filename: covbadge.svg
          label: Coverage
          message: ${{ env.total }}%
          minColorRange: 50
          maxColorRange: 90
          valColorRange: ${{ env.total }}
