# Config file for inference scheme

# Set seed for reproducibility
seed = 42

# Logging level ("DEBUG", "INFO", "WARNING", "ERROR")
logging = "INFO"

# Path to output folder where inference will be saved (relative to PROTEUS output folder)
output = "bayesopt_sn"

# Path to base (reference) config file relative to PROTEUS root folder
ref_config = "input/ensembles/example.toml"

# Method for initialising the inference scheme (one of these must be 'none')
init_samps = 2        # Number of random samples if starting from scratch.
init_grid  = 'none' # grid_demo/'   # Path pre-computed grid (relative to PROTEUS output folder)

# Parameters for Bayesian optimisation
n_workers  = 10        # Number of parallel workers
kernel     = "MAT3/2"    # Kernel type for GP, "RBF" | "MAT1/2" | "MAT3/2" | "MAT5/2"
acqf       = "LogEI"  # Acquisition function, "UCB" | "LogEI" | "E-LogEI"
n_steps    = 10       # Total number of evaluations (i.e. BO steps)

# Parameters to optimize (with bounds)
[parameters]
"params.stop.time.maximum"  = [1e7,     6e9]
"orbit.semimajoraxis"       = [0.01,    0.5]
"struct.mass_tot"           = [0.3,     5.0]
"struct.corefrac"           = [0.2,     0.8]
"outgas.fO2_shift_IW"       = [-4.0,    5.0]
"delivery.elements.H_ppmw"  = [1e2,     30000.0]
"delivery.elements.CH_ratio"= [0.1,     10.0]
"delivery.elements.SH_ratio"= [0.1,     10.0]

# Target observables to match by optimisation
[observables]
"M_planet"       = 2.3885446605e+25  # SN
# "M_planet"       = 1.1931358028e+25  # SE
# "M_planet"       = 5.9656593339e+24  # TR

"R_obs"          = 1.0068775762e+07  # SN
# "R_obs"          = 7e6  # SE
# "R_obs"          = 7e6  # TR

"T_obs"          = 2.4356164276e+02 # SN
# "T_obs"          = 288.0 # SE
# "T_obs"          = 288.0 # TR

"atm_kg_per_mol" = 1.1510662518e-02  # SN
# "atm_kg_per_mol" = 1.8599980012e-02  # SE
# "atm_kg_per_mol" = 2.9627359320e-02  # TR

"C/O_atm"        = 1.9420040981089646   # SN
# "C/O_atm"        = 1.0579221525822065   # SE
# "C/O_atm"        = 0.22754965161883398   # TR

"S/O_atm"        = 3.884008205522587   # SN
# "S/O_atm"        = 0.5289610796935059   # SE
# "S/O_atm"        = 0.11377483158360908   # TR
