# Config file for inference scheme

# Set seed for reproducibility
seed = 42

# Logging level ("DEBUG", "INFO", "WARNING", "ERROR")
logging = "INFO"

# Path to output folder where inference will be saved (relative to PROTEUS output folder)
output = "bayesopt_infer"

# Path to base (reference) config file relative to PROTEUS root folder
ref_config = "input/ensembles/example.toml"

# Method for initialising the inference scheme (one of these must be 'none')
init_samps = 3        # Number of random samples if starting from scratch.
init_grid  = 'none' # grid_demo/'   # Path pre-computed grid (relative to PROTEUS output folder)

# Parameters for Bayesian optimisation
n_workers  = 13        # Number of parallel workers
kernel     = "MAT3/2"    # Kernel type for GP, "RBF" | "MAT1/2" | "MAT3/2" | "MAT5/2"
acqf       = "LogEI"  # Acquisition function, "UCB" | "LogEI" | "E-LogEI"
n_steps    = 40       # Total number of evaluations (i.e. BO steps)

# Parameters to optimize (with bounds)
[parameters]
"params.stop.time.maximum"  = [1e7,     3e9]
"orbit.semimajoraxis"       = [0.01,    0.5]
"struct.mass_tot"           = [0.5,     5.0]
"struct.corefrac"           = [0.2,     0.8]
"outgas.fO2_shift_IW"       = [-4.0,    5.0]
"delivery.elements.H_ppmw"  = [1e2,     20000.0]
"delivery.elements.CH_ratio"= [0.1,     6.0]
"delivery.elements.SH_ratio"= [0.1,     6.0]


# Target observables to match by optimisation...

# helpfile: /home/harrison/Projects/PROTEUS/output/bayesopt_sn/runtime_helpfile.csv
# extracted at index: 91, time: 4.705e+08 years
# [observables]
#     "M_planet" = 2.1885440062e+25
#     "R_obs" = 1.0647856810e+07
#     "T_obs" = 5.3921109314e+02
#     "atm_kg_per_mol" = 9.7110516465e-03
#     "C/O_atm" = 7.2789869068e-01
#     "S/O_atm" = 2.9116525549e+00

# helpfile: /home/harrison/Projects/PROTEUS/output/bayesopt_se/runtime_helpfile.csv
# extracted at index: 92, time: 2.489e+09 years
# [observables]
#     "M_planet" = 1.0569480216e+25
#     "R_obs" = 8.6610702680e+06
#     "T_obs" = 7.6548047142e+02
#     "atm_kg_per_mol" = 2.0721849495e-02
#     "C/O_atm" = 4.8390309982e-01
#     "S/O_atm" = 2.4195943106e-01


# helpfile: /home/harrison/Projects/PROTEUS/output/bayesopt_tr/runtime_helpfile.csv
# extracted at index: 235, time: 7.998e+08 years
[observables]
    "M_planet" = 6.0737376907e+24
    "R_obs" = 6.2685296226e+06
    "T_obs" = 5.7746514093e+02
    "atm_kg_per_mol" = 2.9583452783e-02
    "C/O_atm" = 2.2682307919e-01
    "S/O_atm" = 1.1362542474e-01

